
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 525 525 1 13 under 133 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if entity @s[y=0,dy=90] run spreadplayers 525 525 1 13 under 133 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 525 525 1 13 under 133 false @s

