
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 104066 104082 3 33 under 164 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 104066 104082 3 33 under 164 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 104066 104082 3 33 under 164 false @s

