
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 41133 40946 2 27 under 188 false @s

## Assurance commands
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 41133 40946 2 27 under 188 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 41133 40946 2 27 under 188 false @s

