
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 41133 40946 2 27 under 188 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 41133 40946 2 27 under 188 false @s

