
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 103066 103082 3 33 under 148 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 103066 103082 3 33 under 148 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 103066 103082 3 33 under 148 false @s

