
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 73038 73041 1 19 under 128 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 73038 73041 1 19 under 128 false @s

