
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 77048 77047 2 23 under 180 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 77048 77047 2 23 under 180 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 77048 77047 2 23 under 180 false @s

