
# Project identification
id: "switch"
name: "Switch"
author: "Stoupy51"
version: "2.0.0"
minecraft: "26.2"

# More directories
directory: "."
output: "build"

# Takes a nested pack config, see PackConfig() documentation
data_pack:
    name: "datapack"
resource_pack:
    name: resource_pack

require:
    - "stewbeet"

# A list of strings or dicts representing "plugins".
pipeline:
    - "src.setup_definitions" # User code
    - "stewbeet.plugins.resource_pack.sounds.silent"
    - "stewbeet.plugins.resource_pack.item_models.silent"
    # - "stewbeet.plugins.resource_pack.check_power_of_2.silent"
    - "stewbeet.plugins.custom_recipes.silent"
    # - "stewbeet.plugins.ingame_manual"
    - "stewbeet.plugins.datapack.loading.silent"
    - "stewbeet.plugins.datapack.custom_blocks.silent"
    - "stewbeet.plugins.datapack.loot_tables.silent"
    - "stewbeet.plugins.datapack.sorters.silent"
    - "stewbeet.plugins.compatibilities.simpledrawer.silent"
    - "stewbeet.plugins.compatibilities.neo_enchant.silent"
    - "src.link" # User code
    - "stewbeet.plugins.finalyze.custom_blocks_ticking.silent"
    - "stewbeet.plugins.finalyze.basic_datapack_structure.silent"
    - "stewbeet.plugins.finalyze.dependencies"
    # - "stewbeet.plugins.finalyze.unload"
    - "stewbeet.plugins.finalyze.check_unused_textures.silent"
    - "stewbeet.plugins.finalyze.last_final.silent"
    - "stewbeet.plugins.auto.scoreboard_constants.silent"
    # - "stewbeet.plugins.auto.lang_file"
    - "stewbeet.plugins.auto.headers.silent"
    - "stewbeet.plugins.archive"
    - "stewbeet.plugins.merge_smithed_weld"
    - "stewbeet.plugins.copy_to_destination"
    - "stewbeet.plugins.compute_sha1.silent"

# Generic dict which holds extra information usable by plugins
meta:
    stewbeet:
        # More directories
        textures_folder: "assets/textures"
        sounds:
            folder: "assets/sounds"
            # Optional: glob patterns to exclude from processing
            exclude_patterns: []
        records_folder: "assets/records"
        libs_folder: "libs"

        # Path where definitions debug information will be dumped
        definitions_debug: "definitions_debug.json"

        # Optional list of destination paths where generated files will be copied
        build_copy_destinations:
            # Paths to copy the datapack(s) to
            datapack: ["_switch_dump","sftp://switch_paralya@coll.paralya.fr/sftp/Switch/datapacks"]
            # Paths to copy the resource pack(s) to
            resource_pack: ["D:/minecraft/snapshot/resourcepacks", "D:/minecraft/latest/resourcepacks"]

        # Automagically checks for dependencies and their minimum required versions at runtime.
        load_dependencies: {
            "sheepwars": {"name":"SheepWars", "url":"https://github.com/Stoupy51/SheepWars","source":"smithed", "smithed_id":"sheepwars"},
            "golf_ball": {"name":"GolfBall", "url":"https://github.com/Stoupy51/GolfBall","source":"modrinth", "modrinth_slug":"golf_ball"},
            "shopping_kart": {"name":"ShoppingKart", "url":"https://github.com/Stoupy51/ShoppingKart","source":"smithed", "smithed_id":"shopping-kart", "has_resource_pack": True},
        }

