
# Project identification
id: "switch"
name: "Switch"
author: "Stoupy51"
version: "2.0.0"
minecraft: "1.21.10"

# More directories
directory: "."
output: "build"

# Takes a nested pack config, see PackConfig() documentation
data_pack:
    name: "datapack"
    load: ["merge/datapack"]
resource_pack:
    name: resource_pack
    load: ["merge/resource_pack"]

require:
    - "stewbeet"

# A list of strings or dicts representing "plugins".
pipeline:
    - "src.setup_definitions" # User code
    - "stewbeet.plugins.verify_definitions"
    - "stewbeet.plugins.resource_pack.sounds"
    - "stewbeet.plugins.resource_pack.item_models"
    - "stewbeet.plugins.resource_pack.check_power_of_2"
    - "stewbeet.plugins.custom_recipes"
    # - "stewbeet.plugins.ingame_manual"
    - "stewbeet.plugins.datapack.loading"
    - "stewbeet.plugins.datapack.custom_blocks"
    - "stewbeet.plugins.datapack.loot_tables"
    - "stewbeet.plugins.datapack.sorters"
    - "stewbeet.plugins.compatibilities.simpledrawer"
    - "stewbeet.plugins.compatibilities.neo_enchant"
    - "src.link" # User code
    - "stewbeet.plugins.finalyze.custom_blocks_ticking"
    - "stewbeet.plugins.finalyze.basic_datapack_structure"
    - "stewbeet.plugins.finalyze.dependencies"
    - "stewbeet.plugins.finalyze.check_unused_textures"
    - "stewbeet.plugins.finalyze.last_final"
    # - "stewbeet.plugins.auto.lang_file"
    - "stewbeet.plugins.auto.headers"
    - "stewbeet.plugins.archive"
    # - "stewbeet.plugins.merge_smithed_weld"
    - "stewbeet.plugins.copy_to_destination"
    - "stewbeet.plugins.compute_sha1"

# Generic dict which holds extra information usable by plugins
meta:
    stewbeet:
        # More directories
        textures_folder: "assets/textures"
        sounds_folder: "assets/sounds"
        records_folder: "assets/records"
        libs_folder: "libs"

        # Path where definitions debug information will be dumped
        definitions_debug: "definitions_debug.json"

        # Optional list of destination paths where generated files will be copied
        build_copy_destinations:
            # Paths to copy the datapack(s) to
            datapack: ["_switch_dump"]
            # Paths to copy the resource pack(s) to
            resource_pack: ["D:/minecraft/snapshot/resourcepacks", "D:/minecraft/latest/resourcepacks"]

        # Automagically checks for dependencies and their minimum required versions at runtime.
        load_dependencies: {
            "sheepwars": {"version":[2, 1, 0], "name":"SheepWars", "url":"https://github.com/Stoupy51/SheepWars"},
        }

