
## Python script that generates a door fixer: a script that fixes the doors in a map.
import zipfile


# Define the door types
door_types = [
	"oak_door",
	"spruce_door",
	"birch_door",
	"jungle_door",
	"acacia_door",
	"dark_oak_door",
	"mangrove_door",
	"cherry_door",
	"bamboo_door",
	"crimson_door",
	"warped_door",
	"iron_door"
]

# Define the door states
door_states = {
    "facing": ["north", "east", "south", "west"],
    "half": ["upper", "lower"],
}


# Create a .mcfunction file that for each door possibility, runs the two /setblock commands to fix the door
file_content = """
## This file is automatically generated by 'door_fixer_generator.py', do not edit it manually!
"""


# Write every line
for door_type in door_types:
	for facing in door_states["facing"]:
		for half in door_states["half"]:
			file_content += f"""fill ~-40 ~ ~-40 ~40 ~ ~40 command_block{{Command:"function door_fixer:fix_door_{door_type}_{facing}_{half}",auto:1b}} replace {door_type}[facing={facing},half={half}]\n"""

# Create the data pack
with zipfile.ZipFile("door_fixer.zip", "w") as zip_file:
	
	# Write the pack.mcmeta file
	zip_file.writestr("pack.mcmeta", """{
	"pack": {
		"pack_format": 15,
		"description": "Door Fixer [v1.0]"
	}
}""")

	# Write the data pack
	zip_file.writestr("data/door_fixer/functions/fix_door.mcfunction", file_content)

	# Write the functions that fix the doors
	for door_type in door_types:
		for facing in door_states["facing"]:
			for half in door_states["half"]:
				other_half = "upper" if half == "lower" else "lower"
				offset = "-1" if half == "upper" else "1"
				content = f"""setblock ~ ~ ~ {door_type}[facing={facing},half={half}]\n"""
				content += f"""setblock ~ ~{offset} ~ {door_type}[facing={facing},half={other_half}]"""
				zip_file.writestr(f"data/door_fixer/functions/fix_door_{door_type}_{facing}_{half}.mcfunction", content)

