
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 26030 25986 2 21 under 198 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=163] run spreadplayers 26030 25986 2 21 under 198 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 26030 25986 2 21 under 198 false @s

