
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 14000 14000 4 49 under 254 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if entity @s[y=0,dy=-1] run spreadplayers 14000 14000 4 49 under 254 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 14000 14000 4 49 under 254 false @s

