
# ruff: noqa: E501
# Imports
from stewbeet import Mem, write_function


def write_translations():
	""" Write the spectres_game translation functions at switch:modes/spectres_game/translations/* """
	path: str = f"{Mem.ctx.project_id}:modes/spectres_game/translations"

	# /death_for_global
	write_function(f"{path}/death_for_global", r"""
# French
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=1}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, il était un "},{"text":"Spectre","color":"yellow"},{"text":" !"}]
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=2}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, il était un "},{"text":"Visible","color":"green"},{"text":" !"}]
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=3}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, il était un "},{"text":"Spectror","color":"red"},{"text":" !"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=1}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, c'était un "},{"text":"Spectre","color":"yellow"},{"text":" !"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=2}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, c'était un "},{"text":"Visible","color":"green"},{"text":" !"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=3}] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Le joueur "},{"nbt":"data.name","entity":"@s"},{"text":" est mort, c'était un "},{"text":"Spectror","color":"red"},{"text":" !"}]

# English
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=1}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, they was a "},{"text":"Spectre","color":"yellow"},{"text":"!"}]
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=2}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, they was a "},{"text":"Visible","color":"green"},{"text":"!"}]
execute if score #success switch.data matches 0 if entity @s[scores={switch.alive=3}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, they was a "},{"text":"Spectror","color":"red"},{"text":"!"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=1}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, "},{"text":"Spectre","color":"yellow"},{"text":" they was!"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=2}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, "},{"text":"Visible","color":"green"},{"text":" they was!"}]
execute if score #success switch.data matches 1 if entity @s[scores={switch.alive=3}] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" The player "},{"nbt":"data.name","entity":"@s"},{"text":" died, "},{"text":"Spectror","color":"red"},{"text":" they was!"}]
""")

	# /detect_end
	write_function(f"{path}/detect_end", r"""
# French
execute if score #spectres_game_seconds switch.data matches 900 if score #game_state switch.data matches 0 run tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Fin de partie, temps écoulé ! Aucun des camps n'est sorti vainqueur au bout de 10 minutes !"}]
execute if score #game_state switch.data matches 1 run tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Fin de partie, victoire des "},{"text":"visibles","color":"green"},{"text":" ! GG à "},{"selector":"@a[scores={switch.alive=1..},team=switch.temp.visible]"}]
execute if score #game_state switch.data matches 2 run tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Fin de partie, victoire des "},{"text":"spectres","color":"yellow"},{"text":" ! GG à "},{"selector":"@a[scores={switch.alive=1..,switch.temp.spectror=0},team=switch.temp.spectre]"}]
execute if score #game_state switch.data matches 3 run tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Fin de partie, aucun des camps n'est sorti vainqueur car il n'y a plus aucun joueur en vie !"}]
execute if score #game_state switch.data matches 4 run tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Victoire du "},{"text":"spectror","color":"red"},{"text":" ! GG à "},{"selector":"@a[scores={switch.alive=1..,switch.temp.spectror=1}]"}]

# English
execute if score #spectres_game_seconds switch.data matches 900 if score #game_state switch.data matches 0 run tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Game over, time up! Neither side is the winner after 10 minutes!"}]
execute if score #game_state switch.data matches 1 run tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Game over, victory for "},{"text":"visibles","color":"green"},{"text":"! GG to "},{"selector":"@a[scores={switch.alive=1..},team=switch.temp.visible]"}]
execute if score #game_state switch.data matches 2 run tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Game over, victory for "},{"text":"spectres","color":"yellow"},{"text":"! GG to "},{"selector":"@a[scores={switch.alive=1..,switch.temp.spectror=0},team=switch.temp.spectre]"}]
execute if score #game_state switch.data matches 3 run tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Game over, neither side has won because there are no players left alive!"}]
execute if score #game_state switch.data matches 4 run tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Victory of the "},{"text":"spectror","color":"red"},{"text":"! GG to "},{"selector":"@a[scores={switch.alive=1..,switch.temp.spectror=1}]"}]
""")

	# /obsidian_effect
	write_function(f"{path}/obsidian_effect", r"""
# French
execute if score #random switch.data matches 0 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu un soin pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 1 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" aobtenu un effet de vitesse pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 2 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu une pomme d'or pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 3 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu un effet d'absorption pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 4 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a réssucité l'un des visibles !\n","color":"white"}]
execute if score #random switch.data matches 4 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu 5 TNT pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 5 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu un effet de résistance pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 5 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Les spectres ont obtenu 2 oeufs de creeper et 2 oeufs de zombie villageois !\n","color":"white"}]
execute if score #random switch.data matches 6 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu un effet d'invisibilité pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 6 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a invoqué 3 Golems de Fer !\n","color":"white"}]
execute if score #random switch.data matches 7 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Tous les visibles ont été téléportés sur l'un d'entre eux !\n","color":"white"}]
execute if score #random switch.data matches 8 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu 10 flèches pour son équipe !\n","color":"white"}]
execute if score #random switch.data matches 8 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a obtenu 10 flèches spectrales pour son équipe.","color":"white"},{"text":"\n"}]
execute if score #random switch.data matches 9 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a infligé un effet de lenteur à l'équipe adverse","color":"white"},{"text":"\n"}]
execute if score #random switch.data matches 10 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a infligé un effet de Glowing aux Spectres","color":"white"},{"text":"\n"}]
execute if score #random switch.data matches 10 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a infligé un effet de Poison aux Visibles","color":"white"},{"text":"\n"}]
execute if score #random switch.data matches 11 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Un visible aléatoire est devenu très puissant temporairement !","color":"aqua"},{"text":"\n"}]
execute if score #random switch.data matches 11 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" a infligé un effet de cécité aux visibles !\n","color":"white"}]
execute if score #random switch.data matches 12 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Les visibles ont obtenu un effet de respiration aquatique !\n","color":"white"}]

# English
execute if score #random switch.data matches 0 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got a care for their team!\n","color":"white"}]
execute if score #random switch.data matches 1 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got a speed effect for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 2 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got a golden apple for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 3 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got an absorption effect for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 4 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" has resurrected one of the visible ones!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 4 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got 5 TNT for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 5 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got a resistance effect for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 5 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Spectres got 2 creeper eggs and 2 zombie villager eggs!\n","color":"white"}]
execute if score #random switch.data matches 6 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got an invisibility effect for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 6 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" summoned 3 Iron Golems!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 7 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"All visible have been teleported to one of them!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 8 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got 10 arrows for their team!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 8 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" got 10 spectral arrows for their team.","color":"white"},{"text":" "}]
execute if score #random switch.data matches 9 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" inflicted a slow effect on the opposing team","color":"white"},{"text":" "}]
execute if score #random switch.data matches 10 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" inflicted a Glowing effect on the Spectres","color":"white"},{"text":" "}]
execute if score #random switch.data matches 10 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" inflicted a Poison effect on the Visibles","color":"white"},{"text":" "}]
execute if score #random switch.data matches 11 if entity @s[team=switch.temp.visible] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"A random visible has become very powerful temporarily!","color":"aqua"},{"text":"\n"}]
execute if score #random switch.data matches 11 if entity @s[team=switch.temp.spectre] run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"selector":"@s","color":"yellow","bold":true},{"text":" inflicted a blindness effect on the visible!","color":"white"},{"text":" "}]
execute if score #random switch.data matches 12 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"Tasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"The visible ones have achieved an aquatic breathing effect!\n","color":"white"}]
""")

	# /roles_announcement
	write_function(f"{path}/roles_announcement", r"""
# French
tellraw @a[scores={switch.lang=0},tag=!detached,team=switch.temp.visible] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Vous êtes "},{"text":"visible","color":"green"},{"text":" ! Vous devez trouver tous les spectres et leur faire cracher leur entrailles pour gagner la partie !"}]
tellraw @a[scores={switch.lang=0},tag=!detached,team=switch.temp.spectre] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Vous êtes un "},{"text":"spectre","color":"yellow"},{"text":" ! Votre objectif est d'exterminer tous les visibles afin de contrôler le serveur ! Pour cela, vous êtes invisible permanent !"}]

# English
tellraw @a[scores={switch.lang=1},tag=!detached,team=switch.temp.visible] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" You are "},{"text":"visible","color":"green"},{"text":"! You must find all the spectres and spit out their entrails to win the game!"}]
tellraw @a[scores={switch.lang=1},tag=!detached,team=switch.temp.spectre] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" You're a "},{"text":"spectre","color":"yellow"},{"text":"! Your goal is to exterminate all the visible ones in order to control the server! To achieve this, you are permanently invisible!"}]
""")

	# /second
	write_function(f"{path}/second", r"""
# French
execute if score #spectres_game_seconds switch.data matches 6 if score #SPECTROR_GAME switch.data matches 1 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" 1 partie sur 5 ! ","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" La partie est un","color":"#F8DBF8"},{"text":" SpectrorGame","bold":true,"color":"light_purple"},{"text":" ! Il y'a donc un traitre parmi l'équipe des invisibles.. Il devra faire son possible pour gagner seul. Attention, si tous les visibles meurent la victoire est donnée aux spectres, il doit donc attaquer rapidement !","color":"#FBDBFB"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 6 if score #SPECTROR_GAME switch.data matches 1 run title @a[scores={switch.lang=0},tag=!detached] title {"text":"Spectror Game","color":"light_purple"}
execute if score #spectres_game_seconds switch.data matches 6 run tellraw @a[scores={switch.lang=0,switch.temp.spectror=1}] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" SpectrorsGame ","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" Tu es un Spectror !\nTu dois gagner seul. Pour ce faire, il faudra que tu veilles à trahir au bon moment tes compères spectres.","color":"#C991F0"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 30 run tellraw @a[scores={switch.lang=0},tag=!detached,team=switch.temp.spectre] ["",{"nbt":"ParalyaAstuceFR","storage":"switch:main","interpret":true},{"text":" Utilisez votre arc pour drainer la vie des joueurs !"}]
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" 1 partie sur 3 ! ","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" La partie est un","color":"#F8DBF8"},{"text":" TasksGame","bold":true,"color":"green"},{"text":" ! Les visibles et les spectres pourront effectuer des tâches en détruisant les blocs d'obsidiennes qui apparaîtront. Elles apporteront des bonus essentiels pour leur équipe.","color":"#FBDBFB"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run title @a[scores={switch.lang=0},tag=!detached] title {"text":"Tasks Game","color":"green"}
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run title @a[scores={switch.lang=0},tag=!detached] subtitle {"text":"Pour les Visibles et Spectres","color":"light_purple"}

# English
execute if score #spectres_game_seconds switch.data matches 6 if score #SPECTROR_GAME switch.data matches 1 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" 1 game out of 5! ","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" The game is a","color":"#F8DBF8"},{"text":" SpectrorGame","bold":true,"color":"light_purple"},{"text":"! So there's a traitor on the invisible team... He'll have to do their best to win alone. Be careful, if all the visible ones die, victory is given to the spectres, so he must attack quickly!","color":"#FBDBFB"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 6 if score #SPECTROR_GAME switch.data matches 1 run title @a[scores={switch.lang=1},tag=!detached] title {"text":"Spectror Game","color":"light_purple"}
execute if score #spectres_game_seconds switch.data matches 6 run tellraw @a[scores={switch.lang=1,switch.temp.spectror=1}] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" SpectrorsGame","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" You're a Spectror!\nYou must win alone. To do so, you'll need to betray your fellow spectres at the right moment.","color":"#C991F0"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 30 run tellraw @a[scores={switch.lang=1},tag=!detached,team=switch.temp.spectre] ["",{"nbt":"ParalyaAstuceEN","storage":"switch:main","interpret":true},{"text":" Use your bow to drain players' health!"}]
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"-------------------------","color":"gray"},{"text":"\n\u25ba","color":"gray"},{"text":" 1 game out of 3! ","bold":true,"color":"red"},{"text":":","bold":true,"color":"gray"},{"text":" The game is a","color":"#F8DBF8"},{"text":" TasksGame","bold":true,"color":"green"},{"text":"! Visibles and spectres can perform tasks by destroying the obsidian blocks that appear. These will bring essential bonuses for their team.","color":"#FBDBFB"},{"text":"\n-------------------------","color":"gray"}]
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run title @a[scores={switch.lang=1},tag=!detached] title {"text":"Tasks Game","color":"green"}
execute if score #spectres_game_seconds switch.data matches 15 if score #TASKS_GAME switch.data matches 1 run title @a[scores={switch.lang=1},tag=!detached] subtitle {"text":"Pour les Visibles et Spectres","color":"light_purple"}
function switch:translations/common/basic_actionbar
""")

	# /start
	write_function(f"{path}/start", r"""
# French
tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Lancement de la partie de Spectres Game dans 10 secondes, un tier des joueurs sont des spectres invisibles laissant des particules d'eau sur leur chemin lorsqu'ils ne sneak pas, ils doivent tuer les joueurs visibles tandis qu'eux doivent survivre et tuer les spectres !"}]
tellraw @a[scores={switch.lang=0},tag=!detached] ["\n",{"nbt":"ParalyaPvPOldFR","storage":"switch:main","interpret":true}]

# English
tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"Paralya","storage":"switch:main","interpret":true},{"text":" Spectres Game starts in 10 seconds, a third of the players are invisible spectres leaving water particles in their path when they don't sneak, they must kill the visible players while they must survive and kill the spectres!"}]
tellraw @a[scores={switch.lang=1},tag=!detached] ["\n",{"nbt":"ParalyaPvPOldEN","storage":"switch:main","interpret":true}]
""")

	# /task_obsidian
	write_function(f"{path}/task_obsidian", r"""
# French
tellraw @a[scores={switch.lang=0},tag=!detached] ["",{"text":"---------------","color":"#DEE2E5"},{"text":"\nTasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Des obsidiennes sont apparues ! Les visibles auront des bonus en les cassant !\n","color":"white"},{"text":"---------------","color":"#DEE2E5"}]

# English
tellraw @a[scores={switch.lang=1},tag=!detached] ["",{"text":"---------------","color":"#DEE2E5"},{"text":"\nTasks Game","bold":true,"color":"green"},{"text":" \u2022 ","bold":true,"color":"gray"},{"text":"Obsidians have appeared! Those visible will get bonuses by breaking them!\n","color":"white"},{"text":"---------------","color":"#DEE2E5"}]
""")
