
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 95109 95101 5 51 under 140 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 95109 95101 5 51 under 140 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 95109 95101 5 51 under 140 false @s

