
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 1000 1100 2 25 under 138 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if entity @s[y=0,dy=94] run spreadplayers 1000 1100 2 25 under 138 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1000 1100 2 25 under 138 false @s

