
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 81021 81002 9 90 under 234 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if entity @s[y=0,dy=-1] run spreadplayers 81021 81002 9 90 under 234 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 81021 81002 9 90 under 234 false @s

