
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 22999 23006 5 51 under 185 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 22999 23006 5 51 under 185 false @s

