
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 59080 59062 3 31 under 146 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 59080 59062 3 31 under 146 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 59080 59062 3 31 under 146 false @s

