
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 70151 70143 7 72 under 163 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 70151 70143 7 72 under 163 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 70151 70143 7 72 under 163 false @s

