
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 8001 8000 1 12 under 130 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 8001 8000 1 12 under 130 false @s

