
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 109029 109023 1 11 under 167 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 109029 109023 1 11 under 167 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 109029 109023 1 11 under 167 false @s

