
# ruff: noqa: E501
# Imports
from stewbeet import Mem, write_function


def write_translations():
	""" Write the traitors_game translation functions at switch:modes/traitors_game/translations/* """
	ns: str = Mem.ctx.project_id
	path: str = f"{ns}:modes/traitors_game/translations"

	# /announce_scenarios
	write_function(f"{path}/announce_scenarios", rf"""
# French
tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Scénarios activés :"}}]
execute if score #sc_solitaire {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] [{{"text":"➤ Innocent solitaire","color":"green","hover_event":{{"action":"show_text","value":{{"text":"Au bout d'une minute, un innocent aléatoire est désigné comme solitaire.\nIl peut être le ninja ou un innocent basique.","color":"gray"}}}}}}]
execute if score #sc_floupy {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] [{{"text":"➤ Floupy","color":"green","hover_event":{{"action":"show_text","value":{{"text":"Le rôle 'Floupy' permet de voler le rôle de celui qu'il tue.\nLa deuxième vie du ninja est annulée en cas de vol.\nLe rôle de la victime est obfusqué.","color":"gray"}}}}}}]
execute if score #sc_silencieux {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] [{{"text":"➤ Silencieux","color":"green","hover_event":{{"action":"show_text","value":{{"text":"Il y a 1/3 chance que le rôle d'un joueur ne soit pas affiché lors de sa mort.\nN'affecte pas les messages de l'inspecteur.\nLe scoreboard à droite est gelé.","color":"gray"}}}}}}]

# English
tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Scenarios enabled:"}}]
execute if score #sc_solitaire {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] [{{"text":"➤ Solitary innocent","color":"green","hover_event":{{"action":"show_text","value":{{"text":"After one minute, a random innocent is designated as the solitaire.\nWhen it dies.","color":"gray"}}}}}}]
execute if score #sc_floupy {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] [{{"text":"➤ Floupy","color":"green","hover_event":{{"action":"show_text","value":{{"text":"The 'Floupy' role allows you to steal the role of whoever you kill.\nThe victim's role is obfuscated.","color":"gray"}}}}}}]
execute if score #sc_silencieux {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] [{{"text":"➤ Silencer","color":"green","hover_event":{{"action":"show_text","value":{{"text":"There's a 1/3 chance that a player's role won't be displayed when they die.\nThe scoreboard on the right is frozen.","color":"gray"}}}}}}]
""")

	# /death_for_detective
	write_function(f"{path}/death_for_detective", rf"""
# French
execute if entity @s[scores={{{ns}.temp.role=0}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était un "}},{{"text":"UWUWUWUWU","color":"gray","obfuscated":true}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était un "}},{{"text":"Innocent","color":"green"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était le "}},{{"text":"Ninja","color":"green"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était un "}},{{"text":"Traitre","color":"red"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était le "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, il était le "}},{{"text":"Floupy","color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, c'était un "}},{{"text":"Innocent","color":"green"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, c'était le "}},{{"text":"Ninja","color":"green"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, c'était un "}},{{"text":"Traitre","color":"red"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, c'était le "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mort, c'était le "}},{{"text":"Floupy","color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mouru, "}},{{"text":"Innocent","color":"green"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mouru, "}},{{"text":"Ninja","color":"green"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mouru, "}},{{"text":"Traitre","color":"red"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mouru, "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["",{{"text":"[Message en avance]","color":"green"}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" est mouru, "}},{{"text":"Floupy","color":"yellow"}},{{"text":" fût son rôle..."}}]

# English
execute if entity @s[scores={{{ns}.temp.role=0}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":"died, they was a "}},{{"text":"UWUWUWUWU","color":"gray","obfuscated":true}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" died, they was an "}},{{"text":"Innocent","color":"green"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" died, they was the "}},{{"text":"Ninja","color":"green"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" died, they was a "}},{{"text":"Traitor","color":"red"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" died, they was the "}},{{"text":"Big Traitor","color":"dark_red"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" died, they was the "}},{{"text":"Floupy","color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" is dead, they was "}},{{"text":"Innocent","color":"green"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" is dead, it was "}},{{"text":"Ninja","color":"green"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" is dead, they was "}},{{"text":"Traitor","color":"red"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" is dead, it was "}},{{"text":"Big Traitor","color":"dark_red"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" is dead, it was "}},{{"text":"Floupy","color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" was deady, "}},{{"text":"Innocent","color":"green"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" was deady, "}},{{"text":"Ninja","color":"green"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" was deady, "}},{{"text":"Traitor","color":"red"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" was deady, "}},{{"text":"Big Traitor","color":"dark_red"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["",{{"text":"[Early message]","color":"green"}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s"}},{{"text":" was deady, "}},{{"text":"Floupy","color":"yellow"}},{{"text":" was their role..."}}]
""")

	# /death_for_global
	write_function(f"{path}/death_for_global", rf"""
# French
execute if entity @s[scores={{{ns}.temp.role=0}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était "}},{{"text":"UWUWUWUWU","color":"gray","obfuscated":true}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était un "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était l'"}},{{"text":"Inspecteur","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était le "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était un "}},{{"text":"Traitre","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était le "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, il était le "}},{{"text":"Floupy","color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était un "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était l'"}},{{"text":"Inspecteur","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était le "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était un "}},{{"text":"Traitre","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était le "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mort, c'était le "}},{{"text":"Floupy","color":"yellow"}},{{"text":" !"}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Inspecteur","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireFR","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Traitre","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Gros Traitre","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" fût son rôle..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Le joueur "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" est mouru, "}},{{"text":"Floupy","color":"yellow"}},{{"text":" fût son rôle..."}}]

# English
execute if entity @s[scores={{{ns}.temp.role=0}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, he was "}},{{"text":"UWUWUWUWU","color":"gray","obfuscated":true}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was an "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was an "}},{{"text":"Inspector","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was the "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was a "}},{{"text":"Traitor","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was the "}},{{"text":"Big Traitor","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 0 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" died, they was the "}},{{"text":"Floupy","color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, they was "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, they was "}},{{"text":"Inspector","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, it was "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, they was "}},{{"text":"Traitor","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, it was "}},{{"text":"Big Traitor","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 1 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" is dead, it was "}},{{"text":"Floupy","color":"yellow"}},{{"text":"!"}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=2}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Innocent","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=1}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Inspector","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=3..4}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Ninja","color":"green"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"nbt":"solitaireEN","storage":"{ns}:temp","interpret":true,"color":"dark_aqua"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=5}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Traitor","color":"red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=6}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Big Traitor","color":"dark_red"}},{{"nbt":"stolen","storage":"{ns}:temp","interpret":true,"color":"yellow"}},{{"text":" was their role..."}}]
execute if score #success {ns}.data matches 2 if entity @s[scores={{{ns}.temp.role=7}}] run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" The player "}},{{"nbt":"data.name","entity":"@s","interpret":true}},{{"text":" was deady, "}},{{"text":"Floupy","color":"yellow"}},{{"text":" was their role..."}}]
""")

	# /death_player
	write_function(f"{path}/death_player", rf"""
# French
tellraw @s[scores={{{ns}.lang=0,{ns}.alive=1..,{ns}.temp.role=4}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes mort mais votre capacité de "}},{{"text":"ninja","color":"green"}},{{"text":" vous permet de revenir dans la partie !"}}]

# English
tellraw @s[scores={{{ns}.lang=1,{ns}.alive=1..,{ns}.temp.role=4}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" You're dead but your "}},{{"text":"ninja","color":"green"}},{{"text":" ability lets you get back in the game!"}}]
""")

	# /detect_end
	write_function(f"{path}/detect_end", rf"""
# French
execute if score #game_state {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, victoire des "}},{{"text":"innocents","color":"green"}},{{"text":" ! GG à "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=..4}}]"}}]
execute if score #game_state {ns}.data matches 2 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, victoire des "}},{{"text":"traitres","color":"red"}},{{"text":" ! GG à "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=5}}]"}}]
execute if score #game_state {ns}.data matches 4 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, victoire du "}},{{"text":"gros traitre","color":"dark_red"}},{{"text":" ! GG "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=6}}]"}}]
execute if score #game_state {ns}.data matches 9 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, victoire du "}},{{"text":"solitaire","color":"yellow"}},{{"text":" ! GG "}},{{"selector":"@a[scores={{{ns}.alive=1..}},tag={ns}.solitaire]"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 6 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, temps écoulé ! Victoire des "}},{{"text":"traitres normaux","color":"red"}},{{"text":" car il ne reste aucun innocent et que le gros traitre n'a pas su trahir ! GG à "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=5}}]"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 3 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, temps écoulé ! Aucun des camps n'est sorti vainqueur au bout de 20 minutes !"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 5 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, temps écoulé ! Aucun des camps n'est sorti vainqueur au bout de 20 minutes !"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 7 run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Fin de partie, temps écoulé ! Aucun des camps n'est sorti vainqueur au bout de 20 minutes !"}}]

# English
execute if score #game_state {ns}.data matches 1 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, victory for "}},{{"text":"innocents","color":"green"}},{{"text":"! GG to "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=..4}}]"}}]
execute if score #game_state {ns}.data matches 2 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, victory for "}},{{"text":"traitors","color":"red"}},{{"text":"! GG to "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=5}}]"}}]
execute if score #game_state {ns}.data matches 4 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, victory for "}},{{"text":"big traitor","color":"dark_red"}},{{"text":" ! GG "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=6}}]"}}]
execute if score #game_state {ns}.data matches 9 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, victory of the "}},{{"text":"solitary innocent","color":"yellow"}},{{"text":"! GG "}},{{"selector":"@a[scores={{{ns}.alive=1..}},tag={ns}.solitaire]"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 6 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, time's up! Victory for the "}},{{"text":"normal traitors","color":"red"}},{{"text":" because there are no innocents left and the big traitor didn't know how to betray! GG to "}},{{"selector":"@a[scores={{{ns}.alive=1..,{ns}.temp.role=5}}]"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 3 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, time's up! Neither side is the winner after 20 minutes!"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 5 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, time's up! Neither side is the winner after 20 minutes!"}}]
execute if score #traitors_game_seconds {ns}.data matches 1200 if score #game_state {ns}.data matches 7 run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Game over, time's up! Neither side is the winner after 20 minutes!"}}]
""")

	# /random_items
	write_function(f"{path}/random_items", rf"""
# French
tellraw @s[scores={{{ns}.lang=0}}] {{"text":"Item aléatoire reçu !","color":"dark_purple"}}

# English
tellraw @s[scores={{{ns}.lang=1}}] {{"text":"Item random received!","color":"dark_purple"}}
""")

	# /roles_announcement
	write_function(f"{path}/roles_announcement", rf"""
# French
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes l'"}},{{"text":"Inspecteur","color":"green"}},{{"text":" ! Vous sacrifiez 2 coeurs pour obtenir une information sur un traitre dans la partie au bout d'1m30 après l'annonce des rôles (et 3m00) ! Sauvez les innocents et tuez les traitres, tel est votre mission !"}}]
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=2}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes "}},{{"text":"Innocent","color":"green"}},{{"text":" ! Vous devez trouver tous les traitres et leur faire cracher leur entrailles pour gagner la partie !"}}]
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=3}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes le "}},{{"text":"Ninja","color":"green"}},{{"text":" ! La discrétion est votre atout (ou pas...), vous bénéficiez d'un effet permanent de 15% de vitesse. Lors de votre mort, vous aurez une seconde vie où vous serez limité à 5 coeurs maximum. Servez donc votre peuple et défendez-le des traitres !"}}]
execute if score #starting_count {ns}.data matches ..4 run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=5}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes un "}},{{"text":"Traitre","color":"red"}},{{"text":" ! Votre objectif est d'exterminer tous les innocents afin de contrôler le serveur ! Pour cela, il vous est donné une potion de rage dans votre inventaire, seul les traitre la possède donc faites attention !"}}]
execute if score #starting_count {ns}.data matches 5.. run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=5}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes un "}},{{"text":"Traitre","color":"red"}},{{"text":" ! Votre objectif est d'exterminer tous les innocents afin de contrôler le serveur ! Pour cela, il vous est donné une potion de rage dans votre inventaire, seul les traitre la possède donc faites attention !\nVoici la liste de vos alliés : "}},{{"selector":"@a[scores={{{ns}.temp.role=5..6}},sort=random]"}}]
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=6}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes le "}},{{"text":"Gros Traitre","color":"red"}},{{"text":" ! Après avoir mangé un peu trop de BigMac, vous décidez de contrôler le monde, votre objectif est donc de tuer TOUT le monde afin de contrôler la chaîne de production de BigMac ! Pour cela, il vous est donné une potion de rage dans votre inventaire ainsi que 5 coeurs supplémentaires, seul les traitre la possède donc faites attention !\nVoici la liste des traitres que vous devez berner : "}},{{"selector":"@a[scores={{{ns}.temp.role=5}},sort=random]"}}]
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=7}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous êtes "}},{{"text":"Floupy","color":"yellow"}},{{"text":" ! Vous avez le pouvoir de voler le rôle du premier joueur que vous tuez. Si vous tuez le Ninja, vous l'empêchez d'utiliser sa deuxième vie et vous lui voler son nombre de vie actuel. Vous devez gagner dans le camp dans lequel vous passez."}}]
tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=2..}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" L'inspecteur est "}},{{"selector":"@a[scores={{{ns}.temp.role=1}}]","color":"green"}},{{"text":", donc ne l'accusez pas si vous êtes innocent !"}}]

# English
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You're the "}},{{"text":"Inspector","color":"green"}},{{"text":"! You sacrifice 2 hearts to get information about a traitor in the game after 1m30 after the roles are announced (and 3m00)! Save the innocents and kill the traitors - that's your mission!"}}]
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=2}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You are "}},{{"text":"Innocent","color":"green"}},{{"text":"! You must find all the traitors and spit out their entrails to win the game!"}}]
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=3}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You're the "}},{{"text":"Ninja","color":"green"}},{{"text":"! Stealth is your trump card (or not...), and you benefit from a permanent 15% speed effect. When you die, you'll have a second life where you'll be limited to a maximum of 5 hearts. So serve your people and defend them from traitors!"}}]
execute if score #starting_count {ns}.data matches ..4 run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=5}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You're a "}},{{"text":"traitor","color":"red"}},{{"text":"! Your goal is to exterminate all innocents in order to control the server! To do this, you've been given a rage potion in your inventory, but only traitors have it, so be careful!"}}]
execute if score #starting_count {ns}.data matches 5.. run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=5}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You're a "}},{{"text":"traitor","color":"red"}},{{"text":"! Your goal is to exterminate all innocents in order to control the server! To do this, you're given a rage potion in your inventory, but only traitors have it, so be careful! Here's the list of your allies: "}},{{"selector":"@a[scores={{{ns}.temp.role=5..6}},sort=random]"}}]
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=6}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You're the "}},{{"text":"Big Traitor","color":"red"}},{{"text":"! After eating a few too many BigMacs, you've decided to take control of the world, so your goal is to kill EVERYONE in order to control the BigMac production line! To do this, you've been given a rage potion in your inventory and 5 extra hearts, but only the traitors have the potion, so be careful! Here's the list of traitors you have to fool: "}},{{"selector":"@a[scores={{{ns}.temp.role=5}},sort=random]"}}]
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=7}}] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You are "}},{{"text":"Floupy","color":"yellow"}},{{"text":"! You have the power to steal the role of the first player you kill. If you kill the ninja, you prevent him from using their second life and rob him of their current life count. You must win on the side you switch to."}}]
tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=2..}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" The inspector is "}},{{"selector":"@a[scores={{{ns}.temp.role=1}}]","color":"green"}},{{"text":", so don't accuse him if you're innocent!"}}]
""")

	# /roles_choose_solitaire
	write_function(f"{path}/roles_choose_solitaire", rf"""
# French
tellraw @p[scores={{{ns}.lang=0}},tag={ns}.solitaire] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez été choisi comme Solitaire, soyez le dernier en vie pour gagner la partie !","color":"yellow"}}]

# English
tellraw @p[scores={{{ns}.lang=1}},tag={ns}.solitaire] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" You have been chosen as Solitary, be the last one alive to win the game!","color":"yellow"}}]
""")

	# /roles_vol
	write_function(f"{path}/roles_vol", rf"""
# French
tellraw @s[scores={{{ns}.lang=0}}] [{{"text":"\nFloupy vient de vous voler votre rôle !\n","color":"red"}}]
execute if score #role {ns}.data matches 1 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Inspecteur","color":"green"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 2 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Innocent","color":"green"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 3 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Ninja (seconde vie non-utilisée)","color":"green"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 4 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Ninja (seconde vie utilisée)","color":"green"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 5 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Traitre","color":"red"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 6 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Gros Traitre","color":"red"}},{{"text":" !"}}]
execute if score #role {ns}.data matches 7 run tellraw @p[scores={{{ns}.lang=0}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Vous avez volé le rôle "}},{{"text":"Floupy","color":"yellow"}},{{"text":" !"}}]

# English
tellraw @s[scores={{{ns}.lang=1}}] [{{"text":"\nFloupy just stole your role!\n","color":"red"}}]
execute if score #role {ns}.data matches 1 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Inspector","color":"green"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 2 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Innocent","color":"green"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 3 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Ninja (second life unused)","color":"green"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 4 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Ninja (second life used)","color":"green"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 5 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Traitor","color":"red"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 6 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Big Traitor","color":"red"}},{{"text":"!"}}]
execute if score #role {ns}.data matches 7 run tellraw @p[scores={{{ns}.lang=1}},tag={ns}.temp.floupy] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" You stole the role "}},{{"text":"Floupy","color":"yellow"}},{{"text":"!"}}]
""")

	# /second
	write_function(f"{path}/second", rf"""
# French
execute if score #traitors_game_seconds {ns}.data matches 90 run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" Voici l'identité d'un traitre : "}},{{"selector":"@a[tag=!detached,gamemode=!spectator,scores={{{ns}.temp.role=5..6}},sort=random,limit=1]","color":"green"}},{{"text":" !"}}]
execute if score #traitors_game_seconds {ns}.data matches 180 run tellraw @a[scores={{{ns}.lang=0,{ns}.temp.role=1}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" Voici l'identité d'un traitre : "}},{{"selector":"@a[tag=!detached,gamemode=!spectator,scores={{{ns}.temp.role=5..6}},sort=random,limit=1]","color":"green"}},{{"text":" !"}}]

# English
execute if score #traitors_game_seconds {ns}.data matches 90 run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" This is the identity of a traitor: "}},{{"selector":"@a[tag=!detached,gamemode=!spectator,scores={{{ns}.temp.role=5..6}},sort=random,limit=1]","color":"green"}},{{"text":"!"}}]
execute if score #traitors_game_seconds {ns}.data matches 180 run tellraw @a[scores={{{ns}.lang=1,{ns}.temp.role=1}}] ["\n",{{"nbt":"ParalyaWarning","storage":"{ns}:main","interpret":true}},{{"text":" This is the identity of a traitor: "}},{{"selector":"@a[tag=!detached,gamemode=!spectator,scores={{{ns}.temp.role=5..6}},sort=random,limit=1]","color":"green"}},{{"text":"!"}}]
function {ns}:translations/common/basic_actionbar
""")

	# /start
	write_function(f"{path}/start", rf"""
# French
tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Lancement de la partie de Traitors Game, des traitres seront présents dans la partie avec quelques particularités, vous allez recevoir votre rôle dans quelques secondes !"}}]
tellraw @a[scores={{{ns}.lang=0}},tag=!detached] ["\n",{{"nbt":"ParalyaPvPOldFR","storage":"{ns}:main","interpret":true}}]

# English
tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"Paralya","storage":"{ns}:main","interpret":true}},{{"text":" Launching the Traitors Game, traitors will be present in the game with some peculiarities, you will receive your role in a few seconds!"}}]
tellraw @a[scores={{{ns}.lang=1}},tag=!detached] ["\n",{{"nbt":"ParalyaPvPOldEN","storage":"{ns}:main","interpret":true}}]
""")

	# /summon_lootboxes
	write_function(f"{path}/summon_lootboxes", rf"""
# French
execute unless score #count {ns}.data matches 6.. run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] [{{"text":"Une lootbox est apparue !","color":"green"}}]
execute if score #count {ns}.data matches 6.. run tellraw @a[scores={{{ns}.lang=0}},tag=!detached] [{{"text":"Plusieurs lootboxes sont apparues !","color":"green"}}]

# English
execute unless score #count {ns}.data matches 6.. run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] [{{"text":"A lootbox has appeared!","color":"green"}}]
execute if score #count {ns}.data matches 6.. run tellraw @a[scores={{{ns}.lang=1}},tag=!detached] [{{"text":"Several lootboxes have appeared!","color":"green"}}]
""")
