
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 68012 68015 0 6 under 119 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 68012 68015 0 6 under 119 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 68012 68015 0 6 under 119 false @s

