
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 49000 49000 5 50 under 146 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 49000 49000 5 50 under 146 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 49000 49000 5 50 under 146 false @s

