
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 69074 69053 2 26 under 159 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 69074 69053 2 26 under 159 false @s

