
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 60092 60033 1 16 under 172 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 60092 60033 1 16 under 172 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 60092 60033 1 16 under 172 false @s

