
# Imports
from beet import Advancement
from stewbeet.core import Mem, set_json_encoder


def write_advancements() -> None:
	""" Build the shared/generic advancements explicitly under the switch namespace.
		(Mode-specific advancements live in each mode's resources.py; the visible/* tree is
		generated by src/advancements.) """
	ns: str = Mem.ctx.project_id
	advancements = Mem.ctx.data[ns].advancements

	# Root of the visible advancement tree
	advancements["tutorial"] = set_json_encoder(Advancement({
		"display": {
			"icon": {"id": "minecraft:command_block"},
			"title": {"text": "Switch", "color": "yellow"},
			"description": {"text": "Compléter le tutoriel du Switch", "color": "aqua"},
			"background": "minecraft:gui/advancements/backgrounds/stone",
			"frame": "challenge",
			"show_toast": True,
			"announce_to_chat": True,
			"hidden": False,
		},
		"criteria": {"requirement": {"trigger": "minecraft:impossible"}},
		"requirements": [["requirement"]],
	}))

	# Generic inventory_changed trigger forwarding to the engine signal
	advancements["inventory_changed"] = set_json_encoder(Advancement({
		"criteria": {"requirement": {"trigger": "minecraft:inventory_changed"}},
		"rewards": {"function": f"{ns}:engine/signals/inventory_changed"},
	}))
