
# Imports
from beet import FunctionTag
from stewbeet.core import Mem, write_function

# smart_ore_generation hooks: disable ore generation in the switch (void) dimensions.
# The denied_dimensions body keeps its upstream doc-comment verbatim; the headers plugin merges in
# the auto-detected @within from the function tag below.
DENIED_DIMENSIONS: str = """
#> smart_ore_generation:v1.1/signals/denied_dimensions
#
# @within\t\t\t#smart_ore_generation:v1/signals/denied_dimensions
# @executed\t\t\tas & at the player who triggered the event
# @input score\t\t#authorized smart_ore_generation.data equals to 1 or 0 if another datapack has already denied generation
#
# @english_WARNING
# - You must check the #authorized score matching 1 before executing any commands to prevent reenable generation in a dimension that is disabled by another datapack.
# - Putting the #authorized score to 0 will disable generation in the dimension for every datapack.
#
# @french_WARNING
# - Vous devez vérifier que le score #authorized vaut 1 avant d'exécuter des commandes pour éviter de réactiver la génération dans une dimension qui est désactivée par un autre datapack.
# - Mettre le score #authorized à 0 désactivera la génération dans la dimension pour tous les datapacks.

scoreboard players set #authorized smart_ore_generation.data 0
"""


def write_integrations() -> None:
	""" Recreate the static third-party (smart_ore_generation) integration hooks explicitly:
		two functions (header is regenerated by the headers plugin) and their function tags
		(left with beet's default 2-space encoder, matching the upstream files). """
	write_function("smart_ore_generation:denied_dimensions", DENIED_DIMENSIONS, overwrite=True)
	write_function("smart_ore_generation:fake_enumerate", """
scoreboard players set #smart_ore_generation.major load.status 1000000
""", overwrite=True)

	function_tags = Mem.ctx.data["smart_ore_generation"].function_tags
	function_tags["enumerate"] = FunctionTag({"values": ["smart_ore_generation:fake_enumerate"]})
	function_tags["v1/signals/denied_dimensions"] = FunctionTag({"values": ["smart_ore_generation:denied_dimensions"]})
