
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 52007 51962 5 54 under 191 false @s

## Assurance commands
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 52007 51962 5 54 under 191 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 52007 51962 5 54 under 191 false @s

