
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 52007 51962 5 54 under 191 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 52007 51962 5 54 under 191 false @s

