
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 72103 72110 5 52 under 150 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 72103 72110 5 52 under 150 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 72103 72110 5 52 under 150 false @s

