
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 100081 100051 2 26 under 124 false @s

## Assurance commands
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 100081 100051 2 26 under 124 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 100081 100051 2 26 under 124 false @s

