
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 100096 100079 3 39 under 168 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 100096 100079 3 39 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 100096 100079 3 39 under 168 false @s

