
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 80071 80071 3 35 under 296 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if entity @s[y=-64,dy=149] run spreadplayers 80071 80071 3 35 under 296 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 80071 80071 3 35 under 296 false @s

