
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 29009 29000 0 6 under 254 false @s

## Assurance commands
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if entity @s[y=100,dy=-1] run spreadplayers 29009 29000 0 6 under 254 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 29009 29000 0 6 under 254 false @s

