
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 2001 2000 2 27 under 169 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 2001 2000 2 27 under 169 false @s

