
# Imports
from stewbeet.core import Block, Item, VanillaBlock, VANILLA_BLOCK_FOR_ORES


# Setup misc items
def setup_misc_items() -> None:
	""" Setup misc items """
	Item(id="letter")
	Item(id="awakened_stardust_bow", base_item="minecraft:bow")
	Item(id="awakened_stardust_sniper", override_model={"parent": "minecraft:item/handheld"})
	# awakened_stardust_block is auto-generated, just set vanilla_block
	Block.from_id("awakened_stardust_block").vanilla_block = VanillaBlock(id="stone")
	Item(id="stardust_bow", base_item="minecraft:bow")
	Item(id="stardust_sniper", override_model={"parent": "minecraft:item/handheld"})
	Item(id="ultimate_bow", base_item="minecraft:bow")
	Item(id="ultimate_sniper", override_model={"parent": "minecraft:item/handheld"})
	Item(id="ultimate_elytra", base_item="minecraft:elytra")
	Item(id="ultimate_bullet")
	Item(id="ultimate_fragment")
	Item(id="ultimate_core")
	# stardust_fragment and stardust_essence are NOT auto-generated by generate_everything_about_these_materials
	Item(id="stardust_essence")
	Item(id="stardust_config", override_model={"parent": "block/command_block"})
	# stardust_block, legendarium_block, solarium_block, darkium_block are auto-generated, just set vanilla_block
	Block.from_id("stardust_block").vanilla_block = VanillaBlock(id="diamond_block")
	Block(id="ender_stardust_ore", vanilla_block=VANILLA_BLOCK_FOR_ORES, no_silk_touch_drop="stardust_essence")
	Block(id="nether_stardust_ore", vanilla_block=VANILLA_BLOCK_FOR_ORES, no_silk_touch_drop="stardust_ingot")
	Block.from_id("legendarium_block").vanilla_block = VanillaBlock(id="lime_concrete")
	Block.from_id("solarium_block").vanilla_block = VanillaBlock(id="orange_concrete")
	Block.from_id("darkium_block").vanilla_block = VanillaBlock(id="black_concrete")
	Item(id="dragon_pearl", base_item="minecraft:ender_pearl")
	Item(id="life_crystal", base_item="minecraft:golden_apple")
	Item(id="stardust_apple", components={
		"consumable": {"on_consume_effects": [{
			"type": "minecraft:apply_effects",
			"effects": [
				{"amplifier": 2, "duration": 100, "id": "minecraft:regeneration", "show_icon": True},
				{"amplifier": 1, "duration": 2400, "id": "minecraft:absorption", "show_icon": True},
			],
		}]},
		"food": {"can_always_eat": True, "nutrition": 4, "saturation": 9.6},
	})
	Item(id="dog_excrement")
	Item(id="quarry_configurator")
	Item(id="travel_staff", override_model={"parent": "minecraft:item/handheld"})
	Item(id="wormhole_potion", override_model={"parent": "minecraft:item/handheld"})
	Item(id="banana", components={"food": {"can_always_eat": True, "nutrition": 5, "saturation": 6}})
	Item(id="anti_radiation_glove", override_model={"parent": "minecraft:item/handheld"})
	Item(id="californium_core")
	Item(id="californium_waste")
	Item(id="radioactive_waste")
	Block(id="radioactive_waste_barrel", vanilla_block=VanillaBlock(id="emerald_block"))
	Item(id="uranium_shard")
	Item(id="chargeless_wand", override_model={"parent": "minecraft:item/handheld"})
	Item(id="fertilizer_wand", override_model={"parent": "minecraft:item/handheld"})
	Item(id="fireball_wand", override_model={"parent": "minecraft:item/handheld"})
	Item(id="shield_wand", override_model={"parent": "minecraft:item/handheld"})
	Item(id="storm_wand", override_model={"parent": "minecraft:item/handheld"})
	Item(id="souls_bag")
	Item(id="souls_bag_half_filled")
	Item(id="souls_bag_filled")

	# Shaders background
	Item(id="bg_black_hole", override_model={"parent":"minecraft:block/cube_all"})

