
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 96123 96119 6 60 under 149 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if entity @s[y=-63,dy=162] run spreadplayers 96123 96119 6 60 under 149 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 96123 96119 6 60 under 149 false @s

