
## This file is generated by the 'generate_survival_folder.py' script
## Do not edit this file but the script instead

# Regenerate the survival maps
execute if data storage switch:main {map:"laser_game"} run function switch:maps/survival/laser_game/regenerate
execute if data storage switch:main {map:"pitchout_1"} run function switch:maps/survival/pitchout_1/regenerate
execute if data storage switch:main {map:"traitor_original"} run function switch:maps/survival/traitor_original/regenerate
execute if data storage switch:main {map:"zone_51"} run function switch:maps/survival/zone_51/regenerate
execute if data storage switch:main {map:"spectre_original"} run function switch:maps/survival/spectre_original/regenerate
execute if data storage switch:main {map:"glassrunner"} run function switch:maps/survival/glassrunner/regenerate
execute if data storage switch:main {map:"mushroom_plains"} run function switch:maps/survival/mushroom_plains/regenerate
execute if data storage switch:main {map:"friends_black_ball"} run function switch:maps/survival/friends_black_ball/regenerate
execute if data storage switch:main {map:"enchanting_island"} run function switch:maps/survival/enchanting_island/regenerate
execute if data storage switch:main {map:"friends_oneforall"} run function switch:maps/survival/friends_oneforall/regenerate
execute if data storage switch:main {map:"warden_forest"} run function switch:maps/survival/warden_forest/regenerate
execute if data storage switch:main {map:"friends_pvpbox_ice"} run function switch:maps/survival/friends_pvpbox_ice/regenerate
execute if data storage switch:main {map:"friends_pvpbox_hills"} run function switch:maps/survival/friends_pvpbox_hills/regenerate
execute if data storage switch:main {map:"friends_pvpbox_end"} run function switch:maps/survival/friends_pvpbox_end/regenerate
execute if data storage switch:main {map:"rush_the_point_1"} run function switch:maps/survival/rush_the_point_1/regenerate
execute if data storage switch:main {map:"friends_cube_lobby"} run function switch:maps/survival/friends_cube_lobby/regenerate
execute if data storage switch:main {map:"baby_park"} run function switch:maps/survival/baby_park/regenerate
execute if data storage switch:main {map:"bowser_castle"} run function switch:maps/survival/bowser_castle/regenerate
execute if data storage switch:main {map:"snow_travel"} run function switch:maps/survival/snow_travel/regenerate
execute if data storage switch:main {map:"cathedrale_liege"} run function switch:maps/survival/cathedrale_liege/regenerate
execute if data storage switch:main {map:"layers_2_teams"} run function switch:maps/survival/layers_2_teams/regenerate
execute if data storage switch:main {map:"spleef_1"} run function switch:maps/survival/spleef_1/regenerate
execute if data storage switch:main {map:"de_a_coudre_1"} run function switch:maps/survival/de_a_coudre_1/regenerate
execute if data storage switch:main {map:"mlg_a_coudre_1"} run function switch:maps/survival/mlg_a_coudre_1/regenerate
execute if data storage switch:main {map:"zonweeb_main"} run function switch:maps/survival/zonweeb_main/regenerate
execute if data storage switch:main {map:"jayl_dark_forest"} run function switch:maps/survival/jayl_dark_forest/regenerate
execute if data storage switch:main {map:"operation_pigclaw"} run function switch:maps/survival/operation_pigclaw/regenerate
execute if data storage switch:main {map:"pitch_creep_2"} run function switch:maps/survival/pitch_creep_2/regenerate
execute if data storage switch:main {map:"dark_forest_hills"} run function switch:maps/survival/dark_forest_hills/regenerate
execute if data storage switch:main {map:"paralya_lobby_noel"} run function switch:maps/survival/paralya_lobby_noel/regenerate
execute if data storage switch:main {map:"huge_cargo"} run function switch:maps/survival/huge_cargo/regenerate
execute if data storage switch:main {map:"ghost_town"} run function switch:maps/survival/ghost_town/regenerate
execute if data storage switch:main {map:"taroatlas_soviet_prison"} run function switch:maps/survival/taroatlas_soviet_prison/regenerate
execute if data storage switch:main {map:"desert_grand_library"} run function switch:maps/survival/desert_grand_library/regenerate
execute if data storage switch:main {map:"new_grounds"} run function switch:maps/survival/new_grounds/regenerate
execute if data storage switch:main {map:"cookie_wars"} run function switch:maps/survival/cookie_wars/regenerate
execute if data storage switch:main {map:"snow_hills"} run function switch:maps/survival/snow_hills/regenerate
execute if data storage switch:main {map:"vilarles_castillo"} run function switch:maps/survival/vilarles_castillo/regenerate
execute if data storage switch:main {map:"zonweeb_highschool"} run function switch:maps/survival/zonweeb_highschool/regenerate
execute if data storage switch:main {map:"enigma_lab_1"} run function switch:maps/survival/enigma_lab_1/regenerate
execute if data storage switch:main {map:"sumo_lawef"} run function switch:maps/survival/sumo_lawef/regenerate
execute if data storage switch:main {map:"find_the_shulker"} run function switch:maps/survival/find_the_shulker/regenerate
execute if data storage switch:main {map:"scartmania"} run function switch:maps/survival/scartmania/regenerate
execute if data storage switch:main {map:"colliseum"} run function switch:maps/survival/colliseum/regenerate
execute if data storage switch:main {map:"scary_labyrinth"} run function switch:maps/survival/scary_labyrinth/regenerate
execute if data storage switch:main {map:"snk_tower"} run function switch:maps/survival/snk_tower/regenerate
execute if data storage switch:main {map:"blindtest"} run function switch:maps/survival/blindtest/regenerate
execute if data storage switch:main {map:"kart_racer_relai"} run function switch:maps/survival/kart_racer_relai/regenerate
execute if data storage switch:main {map:"orange_rings"} run function switch:maps/survival/orange_rings/regenerate
execute if data storage switch:main {map:"find_the_wool"} run function switch:maps/survival/find_the_wool/regenerate
execute if data storage switch:main {map:"snk_lab_s11"} run function switch:maps/survival/snk_lab_s11/regenerate
execute if data storage switch:main {map:"plucky_penguins"} run function switch:maps/survival/plucky_penguins/regenerate
execute if data storage switch:main {map:"warden_escape_statue"} run function switch:maps/survival/warden_escape_statue/regenerate
execute if data storage switch:main {map:"giant_zoo"} run function switch:maps/survival/giant_zoo/regenerate
execute if data storage switch:main {map:"hider_mansion"} run function switch:maps/survival/hider_mansion/regenerate
execute if data storage switch:main {map:"nuketown"} run function switch:maps/survival/nuketown/regenerate
execute if data storage switch:main {map:"enigma_lab_2"} run function switch:maps/survival/enigma_lab_2/regenerate
execute if data storage switch:main {map:"layers_4_teams"} run function switch:maps/survival/layers_4_teams/regenerate
execute if data storage switch:main {map:"snk_lab_s9"} run function switch:maps/survival/snk_lab_s9/regenerate
execute if data storage switch:main {map:"sky_island_tower"} run function switch:maps/survival/sky_island_tower/regenerate
execute if data storage switch:main {map:"sprucy_village"} run function switch:maps/survival/sprucy_village/regenerate
execute if data storage switch:main {map:"survival_boat"} run function switch:maps/survival/survival_boat/regenerate
execute if data storage switch:main {map:"sky_tower"} run function switch:maps/survival/sky_tower/regenerate
execute if data storage switch:main {map:"purple_sky_island"} run function switch:maps/survival/purple_sky_island/regenerate
execute if data storage switch:main {map:"lava_castle"} run function switch:maps/survival/lava_castle/regenerate
execute if data storage switch:main {map:"spruce_dojo"} run function switch:maps/survival/spruce_dojo/regenerate
execute if data storage switch:main {map:"highland_mansion"} run function switch:maps/survival/highland_mansion/regenerate
execute if data storage switch:main {map:"sakura_house"} run function switch:maps/survival/sakura_house/regenerate
execute if data storage switch:main {map:"red_temple"} run function switch:maps/survival/red_temple/regenerate
execute if data storage switch:main {map:"nature_house"} run function switch:maps/survival/nature_house/regenerate
execute if data storage switch:main {map:"flower_village"} run function switch:maps/survival/flower_village/regenerate
execute if data storage switch:main {map:"japanese_village"} run function switch:maps/survival/japanese_village/regenerate
execute if data storage switch:main {map:"whity_lab"} run function switch:maps/survival/whity_lab/regenerate
execute if data storage switch:main {map:"snowy_village"} run function switch:maps/survival/snowy_village/regenerate
execute if data storage switch:main {map:"werewolf_village"} run function switch:maps/survival/werewolf_village/regenerate
execute if data storage switch:main {map:"wyvern_towers"} run function switch:maps/survival/wyvern_towers/regenerate
execute if data storage switch:main {map:"lg_medieval"} run function switch:maps/survival/lg_medieval/regenerate
execute if data storage switch:main {map:"lg_village"} run function switch:maps/survival/lg_village/regenerate
execute if data storage switch:main {map:"lightium_spawn"} run function switch:maps/survival/lightium_spawn/regenerate

# Remove the map from the storage
data remove storage switch:main map

