
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 45962 46018 8 84 under 253 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if entity @s[y=-64,dy=191] run spreadplayers 45962 46018 8 84 under 253 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 45962 46018 8 84 under 253 false @s

