
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 108089 108064 3 32 under 139 false @s

## Assurance commands
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if entity @s[y=-63,dy=162] run spreadplayers 108089 108064 3 32 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 108089 108064 3 32 under 139 false @s

