
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 3000 3000 12 125 under 255 false @s

## Assurance commands
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if entity @s[y=-64,dy=-1] run spreadplayers 3000 3000 12 125 under 255 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 3000 3000 12 125 under 255 false @s

