
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 36083 35924 12 128 under 198 false @s

## Assurance commands
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if entity @s[y=-64,dy=163] run spreadplayers 36083 35924 12 128 under 198 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 36083 35924 12 128 under 198 false @s

