
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 36083 35924 12 128 under 198 false @a

## Assurance commands
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s
execute as @a at @s if entity @s[y=-64,dy=99] run spreadplayers 36083 35924 12 128 under 198 false @s

