
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 53992 54047 0 8 under 139 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 53992 54047 0 8 under 139 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 53992 54047 0 8 under 139 false @s

