
## This file is auto-generated by the script in the same folder, do not edit this file
# Top
tellraw @s ["\n",{"nbt":"ParalyaMusic","storage":"switch:main","interpret":true},{"text":" Gestionnaire de musique","color":"dark_purple"}]
tellraw @s [{"text":"[Pause/Unpause]","color":"green","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 2"}},{"text":" [Stop]\n","color":"red","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 3"}}]

# For each music, write a line
execute if score @s switch.music.current matches 100 run tellraw @s [{"text":"➤ At The Speed Of Light","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 100"}}]
execute unless score @s switch.music.current matches 100 run tellraw @s [{"text":"➤ At The Speed Of Light","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 100"}}]
execute if score @s switch.music.current matches 101 run tellraw @s [{"text":"➤ Fingerdash","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 101"}}]
execute unless score @s switch.music.current matches 101 run tellraw @s [{"text":"➤ Fingerdash","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 101"}}]
execute if score @s switch.music.current matches 102 run tellraw @s [{"text":"➤ Ludicrous Speed","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 102"}}]
execute unless score @s switch.music.current matches 102 run tellraw @s [{"text":"➤ Ludicrous Speed","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 102"}}]
execute if score @s switch.music.current matches 103 run tellraw @s [{"text":"➤ Never Gonna Give You Up","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 103"}}]
execute unless score @s switch.music.current matches 103 run tellraw @s [{"text":"➤ Never Gonna Give You Up","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 103"}}]
execute if score @s switch.music.current matches 104 run tellraw @s [{"text":"➤ Stay Inside Me","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 104"}}]
execute unless score @s switch.music.current matches 104 run tellraw @s [{"text":"➤ Stay Inside Me","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 104"}}]
execute if score @s switch.music.current matches 105 run tellraw @s [{"text":"➤ Stereo Madness","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 105"}}]
execute unless score @s switch.music.current matches 105 run tellraw @s [{"text":"➤ Stereo Madness","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 105"}}]
execute if score @s switch.music.current matches 106 run tellraw @s [{"text":"➤ The Maze Of Mayonnaise","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 106"}}]
execute unless score @s switch.music.current matches 106 run tellraw @s [{"text":"➤ The Maze Of Mayonnaise","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 106"}}]
execute if score @s switch.music.current matches 107 run tellraw @s [{"text":"➤ Unravel","color":"#FFC0CB","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 107"}}]
execute unless score @s switch.music.current matches 107 run tellraw @s [{"text":"➤ Unravel","color":"light_purple","clickEvent":{"action":"run_command","value":"/trigger switch.trigger.music set 107"}}]

