
## This file is auto-generated by the script in the same folder, do not edit this file
execute if score @s switch.music.current matches 1 run function switch:music/ticks/at_the_speed_of_light
execute if score @s switch.music.current matches 2 run function switch:music/ticks/fingerdash
execute if score @s switch.music.current matches 3 run function switch:music/ticks/ludicrous_speed
execute if score @s switch.music.current matches 4 run function switch:music/ticks/never_gonna_give_you_up
execute if score @s switch.music.current matches 5 run function switch:music/ticks/stay_inside_me
execute if score @s switch.music.current matches 6 run function switch:music/ticks/stereo_madness
execute if score @s switch.music.current matches 7 run function switch:music/ticks/the_maze_of_mayonnaise
execute if score @s switch.music.current matches 8 run function switch:music/ticks/unravel
execute if score @s switch.music.current matches -1 run function switch:music/next_music

