
## This file is autogenerated by the "automatic_advancements.py" script. Do not edit it but the script instead.

# Setup storages
execute unless data storage switch:advancements all run data modify storage switch:advancements all set value []
execute unless data storage switch:advancements all[{id:"jump_green"}] run data modify storage switch:advancements all append value {id:"jump_green",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_white"}] run data modify storage switch:advancements all append value {id:"jump_white",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_blue"}] run data modify storage switch:advancements all append value {id:"jump_blue",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_yellow"}] run data modify storage switch:advancements all append value {id:"jump_yellow",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_red"}] run data modify storage switch:advancements all append value {id:"jump_red",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_brown"}] run data modify storage switch:advancements all append value {id:"jump_brown",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_purple"}] run data modify storage switch:advancements all append value {id:"jump_purple",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_dripstone"}] run data modify storage switch:advancements all append value {id:"jump_dripstone",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_bricks"}] run data modify storage switch:advancements all append value {id:"jump_bricks",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:"jump_pink"}] run data modify storage switch:advancements all append value {id:"jump_pink",percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:1}] run data modify storage switch:advancements all append value {id:1,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:2}] run data modify storage switch:advancements all append value {id:2,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:3}] run data modify storage switch:advancements all append value {id:3,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:4}] run data modify storage switch:advancements all append value {id:4,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:5}] run data modify storage switch:advancements all append value {id:5,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:6}] run data modify storage switch:advancements all append value {id:6,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:7}] run data modify storage switch:advancements all append value {id:7,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:8}] run data modify storage switch:advancements all append value {id:8,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:9}] run data modify storage switch:advancements all append value {id:9,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:10}] run data modify storage switch:advancements all append value {id:10,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:11}] run data modify storage switch:advancements all append value {id:11,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:12}] run data modify storage switch:advancements all append value {id:12,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:13}] run data modify storage switch:advancements all append value {id:13,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:14}] run data modify storage switch:advancements all append value {id:14,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:15}] run data modify storage switch:advancements all append value {id:15,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:16}] run data modify storage switch:advancements all append value {id:16,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:17}] run data modify storage switch:advancements all append value {id:17,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:18}] run data modify storage switch:advancements all append value {id:18,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:19}] run data modify storage switch:advancements all append value {id:19,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:20}] run data modify storage switch:advancements all append value {id:20,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:21}] run data modify storage switch:advancements all append value {id:21,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:22}] run data modify storage switch:advancements all append value {id:22,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:23}] run data modify storage switch:advancements all append value {id:23,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:24}] run data modify storage switch:advancements all append value {id:24,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:25}] run data modify storage switch:advancements all append value {id:25,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:26}] run data modify storage switch:advancements all append value {id:26,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:27}] run data modify storage switch:advancements all append value {id:27,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:28}] run data modify storage switch:advancements all append value {id:28,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:29}] run data modify storage switch:advancements all append value {id:29,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:30}] run data modify storage switch:advancements all append value {id:30,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:31}] run data modify storage switch:advancements all append value {id:31,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:32}] run data modify storage switch:advancements all append value {id:32,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:33}] run data modify storage switch:advancements all append value {id:33,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:34}] run data modify storage switch:advancements all append value {id:34,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:35}] run data modify storage switch:advancements all append value {id:35,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:36}] run data modify storage switch:advancements all append value {id:36,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:37}] run data modify storage switch:advancements all append value {id:37,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:38}] run data modify storage switch:advancements all append value {id:38,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:39}] run data modify storage switch:advancements all append value {id:39,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:40}] run data modify storage switch:advancements all append value {id:40,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:41}] run data modify storage switch:advancements all append value {id:41,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:42}] run data modify storage switch:advancements all append value {id:42,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:43}] run data modify storage switch:advancements all append value {id:43,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:44}] run data modify storage switch:advancements all append value {id:44,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:45}] run data modify storage switch:advancements all append value {id:45,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:46}] run data modify storage switch:advancements all append value {id:46,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:47}] run data modify storage switch:advancements all append value {id:47,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:48}] run data modify storage switch:advancements all append value {id:48,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:49}] run data modify storage switch:advancements all append value {id:49,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:50}] run data modify storage switch:advancements all append value {id:50,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:51}] run data modify storage switch:advancements all append value {id:51,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:52}] run data modify storage switch:advancements all append value {id:52,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:53}] run data modify storage switch:advancements all append value {id:53,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:54}] run data modify storage switch:advancements all append value {id:54,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:55}] run data modify storage switch:advancements all append value {id:55,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:56}] run data modify storage switch:advancements all append value {id:56,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:57}] run data modify storage switch:advancements all append value {id:57,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:58}] run data modify storage switch:advancements all append value {id:58,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:59}] run data modify storage switch:advancements all append value {id:59,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:60}] run data modify storage switch:advancements all append value {id:60,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:61}] run data modify storage switch:advancements all append value {id:61,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:62}] run data modify storage switch:advancements all append value {id:62,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:63}] run data modify storage switch:advancements all append value {id:63,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:64}] run data modify storage switch:advancements all append value {id:64,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:65}] run data modify storage switch:advancements all append value {id:65,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:66}] run data modify storage switch:advancements all append value {id:66,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:67}] run data modify storage switch:advancements all append value {id:67,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:68}] run data modify storage switch:advancements all append value {id:68,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:69}] run data modify storage switch:advancements all append value {id:69,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:70}] run data modify storage switch:advancements all append value {id:70,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:71}] run data modify storage switch:advancements all append value {id:71,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:72}] run data modify storage switch:advancements all append value {id:72,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:73}] run data modify storage switch:advancements all append value {id:73,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:74}] run data modify storage switch:advancements all append value {id:74,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:75}] run data modify storage switch:advancements all append value {id:75,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:76}] run data modify storage switch:advancements all append value {id:76,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:77}] run data modify storage switch:advancements all append value {id:77,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:78}] run data modify storage switch:advancements all append value {id:78,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:79}] run data modify storage switch:advancements all append value {id:79,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:80}] run data modify storage switch:advancements all append value {id:80,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:81}] run data modify storage switch:advancements all append value {id:81,percent:{int:0,digits:0},players:[],total:0}
execute unless data storage switch:advancements all[{id:82}] run data modify storage switch:advancements all append value {id:82,percent:{int:0,digits:0},players:[],total:0}


# Update storages
data modify storage switch:advancements all[{id:"jump_green"}] merge value {color:"blue",auteur:"Stoupy",name:"The Green Jump",description:"Finir le jump vert pour la première fois"}
data modify storage switch:advancements all[{id:"jump_white"}] merge value {color:"blue",auteur:"Stoupy",name:"The White Jump",description:"Finir le jump blanc pour la première fois"}
data modify storage switch:advancements all[{id:"jump_blue"}] merge value {color:"blue",auteur:"Stoupy",name:"The Blue Jump",description:"Finir le jump bleu pour la première fois"}
data modify storage switch:advancements all[{id:"jump_yellow"}] merge value {color:"blue",auteur:"ArtiGrrr",name:"The Yellow Jump",description:"Finir le jump jaune pour la première fois"}
data modify storage switch:advancements all[{id:"jump_red"}] merge value {color:"blue",auteur:"Stoupy",name:"The Red Jump",description:"Finir le jump rouge pour la première fois"}
data modify storage switch:advancements all[{id:"jump_brown"}] merge value {color:"blue",auteur:"OfChara",name:"The Brown Jump",description:"Finir le jump marron pour la première fois"}
data modify storage switch:advancements all[{id:"jump_purple"}] merge value {color:"blue",auteur:"AirDox",name:"The Purple Jump",description:"Finir le jump violet pour la première fois"}
data modify storage switch:advancements all[{id:"jump_dripstone"}] merge value {color:"blue",auteur:"AirDox",name:"The Dripstone Jump",description:"Finir le jump dripstone pour la première fois"}
data modify storage switch:advancements all[{id:"jump_bricks"}] merge value {color:"blue",auteur:"Thitanas",name:"The Bricks Jump",description:"Finir le jump des briques pour la première fois"}
data modify storage switch:advancements all[{id:"jump_pink"}] merge value {color:"blue",auteur:"OfChara",name:"The Pink Jump",description:"Finir le jump rose pour la première fois"}
data modify storage switch:advancements all[{id:1}] merge value {color:"green",auteur:"Stoupy",name:"Bénévolat",description:"Aider à la construction d'une map ou la création d'un mini-jeu"}
data modify storage switch:advancements all[{id:2}] merge value {color:"green",auteur:"Stoupy",name:"Fidèle",description:"Jouez un total de 100 parties sur le Switch"}
data modify storage switch:advancements all[{id:3}] merge value {color:"green",auteur:"Stoupy",name:"La moula",description:"Ayez au moins 400 Saphirs dans votre banque"}
data modify storage switch:advancements all[{id:4}] merge value {color:"green",auteur:"Lawtank",name:"First Victor",description:"Gagnez votre première partie dans n'importe quel mini-jeu"}
data modify storage switch:advancements all[{id:5}] merge value {color:"red",auteur:"GoldVision",name:"Gros Diabète",description:"Gagner une partie de Traitors Game en étant Gros Traitre"}
data modify storage switch:advancements all[{id:6}] merge value {color:"yellow",auteur:"Fhara",name:"Gay Jumper",description:"Terminer le parcours du Gay Shooter"}
data modify storage switch:advancements all[{id:7}] merge value {color:"red",auteur:"TreekoZ",name:"Pitch Slayer",description:"Remporter un Pitchout avec 3 vies"}
data modify storage switch:advancements all[{id:8}] merge value {color:"green",auteur:"Poppiz",name:"Fast Food",description:"Atteignez au moins 50 points en Feed Fast"}
data modify storage switch:advancements all[{id:9}] merge value {color:"red",auteur:"TreekoZ",name:"Bagarreur",description:"Tuez deux personnes dans un délai de 10 secondes en Castagne"}
data modify storage switch:advancements all[{id:10}] merge value {color:"yellow",auteur:"Stoupy",name:"Contre Courant",description:"Réussissez à faire voter au moins 8 personnes un jeu non populaire (Feed Fast, Panic Chase, etc.)"}
data modify storage switch:advancements all[{id:11}] merge value {color:"green",auteur:"Lawtank",name:"Berger",description:"Gagnez une partie de SheepWars sans utiliser aucun mouton (y compris le mouton d'abordage)"}
data modify storage switch:advancements all[{id:12}] merge value {color:"red",auteur:"OfChara",name:"Sans Faute",description:"Gagnez une partie de Spectres Game sans perdre aucun membre de votre équipe."}
data modify storage switch:advancements all[{id:13}] merge value {color:"green",auteur:"Axaltau",name:"Pacifiste",description:"Survivez 100 secondes en PitchOut sans mettre aucun coup"}
data modify storage switch:advancements all[{id:14}] merge value {color:"red",auteur:"Lawtank",name:"The Last King",description:"Soyez le dernier survivant en Protect The King"}
data modify storage switch:advancements all[{id:15}] merge value {color:"yellow",auteur:"Lawtank",name:"Tomahawk",description:"Tuez un joueur en lançant votre couteau en Murder Mystery"}
data modify storage switch:advancements all[{id:16}] merge value {color:"red",auteur:"Lawtank",name:"Héro Humanitaire",description:"Tuez au moins 8 zombies en une partie d'Infected"}
data modify storage switch:advancements all[{id:17}] merge value {color:"red",auteur:"Lawtank",name:"Vive la chair",description:"Infectez 5 survivants dans une partie d'Infected"}
data modify storage switch:advancements all[{id:18}] merge value {color:"red",auteur:"OfChara",name:"Roi fantôme",description:"Tuez 3 personnes en tant que spectre en Spectres Games"}
data modify storage switch:advancements all[{id:19}] merge value {color:"yellow",auteur:"Manu",name:"Wattouat",description:"Mourir à cause d'un moutron foudroyant en SheepWars"}
data modify storage switch:advancements all[{id:20}] merge value {color:"yellow",auteur:"OfChara",name:"Fusée",description:"Dépassez 5 joueurs dans le dernier tour en Kart Racer"}
data modify storage switch:advancements all[{id:21}] merge value {color:"yellow",auteur:"OfChara",name:"Plongeur Expert",description:"Complétez 3 dés à coudre dans les modes de jeu du style"}
data modify storage switch:advancements all[{id:22}] merge value {color:"red",auteur:"OfChara",name:"Homophobe",description:"Mettre au moins 42 flèches en Gay Shooter"}
data modify storage switch:advancements all[{id:23}] merge value {color:"yellow",auteur:"Lawtank",name:"Pélican",description:"Soyez celui ayant le plus de kills en Cigogne (égalité autorisée)"}
data modify storage switch:advancements all[{id:24}] merge value {color:"red",auteur:"Fhara",name:"Feeling The Music",description:"Survivez 20 manches en Block Party"}
data modify storage switch:advancements all[{id:25}] merge value {color:"red",auteur:"OfChara",name:"Ocelot",description:"Ne pas descendre en dessous de la moitié de vie en Creeper Apocalypse"}
data modify storage switch:advancements all[{id:26}] merge value {color:"yellow",auteur:"Marcus",name:"Suicidaire",description:"Soyez la cible de 8 wardens en Warden Escape"}
data modify storage switch:advancements all[{id:27}] merge value {color:"red",auteur:"Megamat",name:"Sam Flynn",description:"Éliminer 3 joueurs avec sa traînée en Moutron"}
data modify storage switch:advancements all[{id:28}] merge value {color:"yellow",auteur:"Megamat",name:"D&Cube",description:"Faites au minimum 50 points en Build Battle"}
data modify storage switch:advancements all[{id:29}] merge value {color:"yellow",auteur:"Marcus",name:"Embrouilleur",description:"Tapez chaque joueur de la partie en Castagne"}
data modify storage switch:advancements all[{id:30}] merge value {color:"red",auteur:"Lawtank",name:"Légende",description:"Gagnez 5 mini-jeux d'affilée"}
data modify storage switch:advancements all[{id:31}] merge value {color:"yellow",auteur:"Xiaojuun",name:"Interville",description:"Mourir en block party à cause d'une vache folle"}
data modify storage switch:advancements all[{id:32}] merge value {color:"yellow",auteur:"Enlaniel",name:"Reste dans ta tombe",description:"Tuez deux fois le ninja dans une partie de Traitors Game"}
data modify storage switch:advancements all[{id:33}] merge value {color:"yellow",auteur:"Megamat",name:"Rush Thief",description:"Sécurisez le drapeau ennemi en Capture/Rush The Flag"}
data modify storage switch:advancements all[{id:34}] merge value {color:"green",auteur:"Megamat",name:"Monopoly",description:"Ramasser 20 lingots d'or en une partie en Murder Mystery"}
data modify storage switch:advancements all[{id:35}] merge value {color:"green",auteur:"Xiaojuun",name:"Daltonien",description:"Meurs à la première manche en Block Party"}
data modify storage switch:advancements all[{id:36}] merge value {color:"green",auteur:"Megamat",name:"Contre son camp",description:"Marcher sur sa propre mine pendant une partie de Landing Mine"}
data modify storage switch:advancements all[{id:37}] merge value {color:"yellow",auteur:"Megamat",name:"Oppenheimer",description:"Survivre plus d'une minute en Bombardement"}
data modify storage switch:advancements all[{id:38}] merge value {color:"yellow",auteur:"Xiaojuun",name:"Regarde ma queue",description:"Avoir une trainée de 15 secondes en moutron"}
data modify storage switch:advancements all[{id:39}] merge value {color:"red",auteur:"ArtiGrrr",name:"Précision Artistique",description:"Finir une partie de Snowball Painter avec exactement 51 points"}
data modify storage switch:advancements all[{id:40}] merge value {color:"yellow",auteur:"Marcus",name:"Harcelé",description:"Mourir 3 fois par la même personne en Pitchout"}
data modify storage switch:advancements all[{id:41}] merge value {color:"red",auteur:"ArtiGrrr",name:"Vengeur",description:"Tuez son assassin en temps que Ninja dans une partie de Traitors Game"}
data modify storage switch:advancements all[{id:42}] merge value {color:"red",auteur:"ArtiGrrr",name:"Xenophobe",description:"Eliminer tous les joueurs d'une même couleur en Layers 4 Teams"}
data modify storage switch:advancements all[{id:43}] merge value {color:"yellow",auteur:"ArtiGrrr",name:"Avide",description:"Détruisez 5 blocs d'obsidienne en une partie de Rush The Point"}
data modify storage switch:advancements all[{id:44}] merge value {color:"yellow",auteur:"Xiaojuun",name:"C'est tout naturel",description:"Poussez un joueur vers un dé à coudre en Simultaneous Jump"}
data modify storage switch:advancements all[{id:45}] merge value {color:"green",auteur:"Lawtank",name:"Humm Charal !",description:"Tuez 10 moutons en une partie de SheepWars"}
data modify storage switch:advancements all[{id:46}] merge value {color:"green",auteur:"Stoupy",name:"Automutilation",description:"Se tuer soi-même avec un mouton en SheepWars"}
data modify storage switch:advancements all[{id:47}] merge value {color:"green",auteur:"luigimario12",name:"Il a rien compris lui",description:"Courir 500 blocs en une partie de Pitchout"}
data modify storage switch:advancements all[{id:48}] merge value {color:"red",auteur:"luigimario12",name:"Donald Trump",description:"Faire au maximum 5 coups en une partie de MiniGolf"}
data modify storage switch:advancements all[{id:49}] merge value {color:"yellow",auteur:"luigimario12",name:"Damidot",description:"Recevoir une note Legendary en Build Battle"}
data modify storage switch:advancements all[{id:50}] merge value {color:"red",auteur:"Stoupy et Lawtank",name:"Zom 100",description:"Terminer le secret de la map Old Japan Apocalypse en Infected"}
data modify storage switch:advancements all[{id:51}] merge value {color:"red",auteur:"Stoupy",name:"Pharaon",description:"Terminer le secret de la map Ancienne Egypte en Infected"}
data modify storage switch:advancements all[{id:52}] merge value {color:"red",auteur:"Stoupy et Lawtank",name:"The Volcano Core",description:"Terminer le secret de la map Lost Graveyard Remastered en Infected"}
data modify storage switch:advancements all[{id:53}] merge value {color:"red",auteur:"Stoupy",name:"Storm Area",description:"Terminer le secret de la map Area51 en Infected"}
data modify storage switch:advancements all[{id:54}] merge value {color:"red",auteur:"Stoupy",name:"Secret Slayer",description:"Terminer les secrets de toutes les maps dans le mode de jeu Infected"}
data modify storage switch:advancements all[{id:55}] merge value {color:"yellow",auteur:"Thitanas",name:"Stomp",description:"Terminer une partie de Rush The Point en atteignant 5000 points"}
data modify storage switch:advancements all[{id:56}] merge value {color:"green",auteur:"Stoupy",name:"Jugeote",description:"Noter les étoiles de 20 mini-jeux différents"}
data modify storage switch:advancements all[{id:57}] merge value {color:"red",auteur:"Goldvision",name:"Survivor",description:"Gagner une partie d'Infecté sans prendre aucun coup en tant qu'humain"}
data modify storage switch:advancements all[{id:58}] merge value {color:"yellow",auteur:"Stoupy",name:"Harceleur",description:"Eliminer 3 fois la même personne en Pitchout"}
data modify storage switch:advancements all[{id:59}] merge value {color:"yellow",auteur:"Stoupy",name:"La plèbe a travaillé pour moi",description:"Remporter une partie de PitchCreep sans tirer une seule flèche"}
data modify storage switch:advancements all[{id:60}] merge value {color:"red",auteur:"Redemoles",name:"Multigamer",description:"Gagner une partie de chaque mini-jeu au moins une fois"}
data modify storage switch:advancements all[{id:61}] merge value {color:"green",auteur:"luigimario12",name:"Héro",description:"Tuez le meurtrier en Murder Mystery en tant qu'innocent"}
data modify storage switch:advancements all[{id:62}] merge value {color:"red",auteur:"OfChara",name:"Chaud les fesses",description:"Remporter une partie de Panic Chase en ayant au maximum 3 coeurs"}
data modify storage switch:advancements all[{id:63}] merge value {color:"green",auteur:"OfChara",name:"Raciste",description:"Tirer sur 3 moutons noirs en une partie de Shoot Da'Sheep"}
data modify storage switch:advancements all[{id:64}] merge value {color:"green",auteur:"Goldvision",name:"Rater son moment de gloire",description:"Mourir sur un cactus, d'une tnt ou de suffocation dans une partie de Murder Mystery"}
data modify storage switch:advancements all[{id:65}] merge value {color:"red",auteur:"Shazin",name:"Régicide",description:"Gagner une partie de Protect The King sans perdre aucun membre de votre royaume"}
data modify storage switch:advancements all[{id:66}] merge value {color:"yellow",auteur:"OfChara",name:"Révolution",description:"Tuer un Roi dans une partie de Beat The Kings"}
data modify storage switch:advancements all[{id:67}] merge value {color:"yellow",auteur:"luigimario12",name:"Tonerre de Zeus",description:"Eliminer 10 joueurs dans une partie de Thunder Spear"}
data modify storage switch:advancements all[{id:68}] merge value {color:"red",auteur:"OfChara",name:"Collatéral",description:"Tuer deux joueurs en Quake avec un seul tir"}
data modify storage switch:advancements all[{id:69}] merge value {color:"green",auteur:"OfChara",name:"Porc-épic",description:"Se prendre 10 flèches en une partie de Gay Shooter"}
data modify storage switch:advancements all[{id:70}] merge value {color:"green",auteur:"Oraclette",name:"Electro-choc",description:"Mourir du rayon d'un Warden en Warden Escape"}
data modify storage switch:advancements all[{id:71}] merge value {color:"yellow",auteur:"Shazin",name:"Merci Gertrude",description:"A partir de la 10ème manche en Block Party, en survivre une grâce à Gertrude"}
data modify storage switch:advancements all[{id:72}] merge value {color:"green",auteur:"luigimario12",name:"C'est donc ça, de se vider...",description:"Lancer 42 boules de neige en une partie de Warden Escape"}
data modify storage switch:advancements all[{id:73}] merge value {color:"red",auteur:"OfChara",name:"Parade Parfaite",description:"Réussir à parer une flèche en lançant son couteau en Murder Mystery"}
data modify storage switch:advancements all[{id:74}] merge value {color:"red",auteur:"OfChara",name:"I am Legend",description:"Gagner une partie d'Infecté en étant le dernier humain (si il y a plus de 10 joueurs)"}
data modify storage switch:advancements all[{id:75}] merge value {color:"yellow",auteur:"OfChara",name:"Tout ça pour ça...",description:"Survivre 42 secondes puis mourir en tombant dans l'eau en Bombardement"}
data modify storage switch:advancements all[{id:76}] merge value {color:"red",auteur:"OfChara",name:"Injustice",description:"Finir le jump en Gay Shooter mais mourir de la main d'un Shooter"}
data modify storage switch:advancements all[{id:77}] merge value {color:"green",auteur:"Stoupy",name:"Pour l'équipe !",description:"Tirer sur la base de bonus dans une partie de Laser Game"}
data modify storage switch:advancements all[{id:78}] merge value {color:"green",auteur:"TreekoZ",name:"Banger sucré au sucre",description:"Préparez un gâteau en une partie de Cooking Festival"}
data modify storage switch:advancements all[{id:79}] merge value {color:"green",auteur:"Thakeax",name:"Le boulet",description:"Mourir du premier coup de canon en Bombardement"}
data modify storage switch:advancements all[{id:80}] merge value {color:"yellow",auteur:"ArtiGrrr",name:"Ooopsy",description:"Se faire tuer par un autre meutrier en tant que meurtrier en Murder Mystery"}
data modify storage switch:advancements all[{id:81}] merge value {color:"green",auteur:"ArtiGrrr",name:"Reviens par ici",description:"Replacer le drapeau de son équipe en Capture/Rush The Flag"}
data modify storage switch:advancements all[{id:82}] merge value {color:"red",auteur:"Stoupy",name:"Bien placé",description:"Survivre 30 secondes sans bouger en Block Party"}

