
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 48000 48000 3 35 under 183 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 48000 48000 3 35 under 183 false @s

