
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 28000 28000 1 15 under 168 false @a

## Assurance commands
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if entity @s[y=63,dy=23] run spreadplayers 28000 28000 1 15 under 168 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 28000 28000 1 15 under 168 false @s

