
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 87022 87047 1 11 under 139 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 87022 87047 1 11 under 139 false @s

