
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 2502 2499 2 21 under 184 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 2502 2499 2 21 under 184 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 2502 2499 2 21 under 184 false @s

