
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 1500 1500 3 39 under 212 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if entity @s[y=0,dy=113] run spreadplayers 1500 1500 3 39 under 212 false @s
execute as @a at @s if block ~ ~-1 ~ barrier run spreadplayers 1500 1500 3 39 under 212 false @s

