
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 89211 89266 10 105 under 193 false @a

## Assurance commands
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s
execute as @a at @s if entity @s[y=0,dy=99] run spreadplayers 89211 89266 10 105 under 193 false @s

