
# Here is a useful link if you want to override autogenerated models: https://github.com/PixiGeko/Minecraft-default-assets/tree/latest/assets/minecraft/models/block

# Imports
import stouputils as stp
from beet import Context
from stewbeet.core import (
	DefaultOre,
	EquipmentsConfig,
	Mem,
	add_item_model_component,
	add_item_name_and_lore_if_missing,
	add_private_custom_data_for_namespace,
	add_smithed_ignore_vanilla_behaviours_convention,
	generate_custom_records,
	generate_everything_about_these_materials,
)

from .database.blocks_behaviors import setup_blocks_behaviors
from .database.infected import setup_infected_items
from .database.misc_items import setup_misc_items
from .database.pvpswap import setup_pvpswap

# Configuration to generate everything about the material based on "steel_ingot"
ORES_CONFIGS: dict[str, EquipmentsConfig|None] = {

	# Custom materials from ImagineYourCraft
	"adamantium_fragment":	EquipmentsConfig(DefaultOre.NETHERITE,	1873,	{"attack_damage": 0.2, "armor": 0.2, "mining_efficiency": 0.2}),
	"sapphire":				EquipmentsConfig(DefaultOre.DIAMOND,	1752,	{"mining_efficiency": 0.2}),
	"ruby":					EquipmentsConfig(DefaultOre.DIAMOND,	1647,	{"attack_damage": 0.5, "armor": 0.5, "mining_efficiency": 0.1}),
	"topaz":				EquipmentsConfig(DefaultOre.DIAMOND,	1281,	{"attack_damage": 1.0, "armor": 1.0}),
	"obsidian_ingot":		EquipmentsConfig(DefaultOre.DIAMOND,	3902,	{"attack_damage": -0.2, "mining_efficiency": -0.2}),
	"steel_ingot":			EquipmentsConfig(DefaultOre.IRON,		444,	{"mining_efficiency": 0.1}),
	"minecraft:emerald":	EquipmentsConfig(DefaultOre.DIAMOND,	736,	{"luck": 0.25}),

	# Custom materials from Stardust Fragment
	"stardust_ingot":		EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),
	"awakened_stardust!":	EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),
	"legendarium_ingot":	EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),
	"solarium_ingot":		EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),
	"darkium_ingot":		EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),
	"ultimate_ingot":		EquipmentsConfig(DefaultOre.DIAMOND,	1812,	{}),

	# Custom materials from CrazyAdventure
	"anti_radiation_stuff":	EquipmentsConfig(DefaultOre.IRON,		250),
	"californium_ingot":	EquipmentsConfig(DefaultOre.DIAMOND,	1953,	{"attack_damage": 0.2, "armor": 0.2, "mining_efficiency": 0.2}),
	"uranium_ingot":		EquipmentsConfig(DefaultOre.NETHERITE,	1812,	{"luck": -0.25}),
}

# Main function should return a database
@stp.measure_time(stp.progress, "Setup definitions")
def beet_default(ctx: Context):
	if Mem.ctx is None:
		Mem.ctx = ctx

	# Generate ores in database & custom disc records
	generate_everything_about_these_materials(ORES_CONFIGS)
	generate_custom_records("auto")

	# More database setup
	setup_misc_items()
	setup_blocks_behaviors()
	setup_infected_items()
	setup_pvpswap()

	# Final adjustments, you definitively should keep them!
	add_item_model_component(black_list = [])
	add_item_name_and_lore_if_missing(black_list = ["element_115"])
	add_private_custom_data_for_namespace()		# Add a custom namespace for easy item detection
	add_smithed_ignore_vanilla_behaviours_convention()	# Smithed items convention
	print()

