""" Build-time validation of the project's declarative data.

Catches at build time what used to only show up in game: a mode without its folder, a group that
nobody declares, a map id with a typo. Every message names the offending declaration and, when it
can, the closest valid value.
"""
# Imports
import json
import re
from dataclasses import dataclass
from difflib import get_close_matches
from pathlib import Path

import stouputils as stp
from stewbeet import Mem

from .datapack.maps.generation.shared_memory import generated_maps
from .datapack.modes.catalogue import GROUPS, GROUPS_BY_ID, MODES
from .datapack.modes.definitions import grouped_modes

# Constants
MODES_FOLDER: Path = Path(__file__).parent / "datapack" / "modes"
""" Folder holding one package per minigame, used to check that every spec has its code. """

RESERVED_FOLDERS: frozenset[str] = frozenset({"_common", "_coupdetat"})
""" Mode folders that are helpers for the engine, never minigames of their own. """

MAPS_OUTSIDE_REGISTRY: frozenset[str] = frozenset({"build_battle", "kart_racer_relai"})
""" Maps that live in the world instead of being generated by the survival map pipeline.

They are the two maps without an intro cinematic, see the note in switch:engine/signals/second.
"""

CHOOSE_MAP_PATTERN: re.Pattern[str] = re.compile(r"choose_map_for\s*\{[^}]*maps:(\[[^\]]*\])")
""" Captures the maps list of a `function switch:maps/choose_map_for {id:"x", maps:[...]}` call. """

MAP_CONDITION_PATTERN: re.Pattern[str] = re.compile(r'\{map:"([a-z0-9_]+)"\}')
""" Captures the map id of a `if data storage switch:main {map:"x"}` condition. """


# Classes
@dataclass(frozen=True)
class Problem:
	""" One validation failure, rendered as a single actionable line. """

	message: str
	""" What is wrong, naming the offending declaration. """

	hint: str = ""
	""" Optional suggestion, ex: the closest valid map id. """

	def render(self) -> str:
		""" The message with its hint appended when there is one.

		Returns:
			str: The line to print

		Examples:
			>>> Problem("mode 'x' has no folder").render()
			"mode 'x' has no folder"
			>>> Problem("unknown map 'tnt_runn'", "did you mean 'tnt_run'?").render()
			"unknown map 'tnt_runn' (did you mean 'tnt_run'?)"
		"""
		return f"{self.message} ({self.hint})" if self.hint else self.message


class Validation:

	@staticmethod
	def suggest(value: str, candidates: list[str]) -> str:
		""" A "did you mean" hint for a value that was not found.

		Args:
			value      (str):       The offending value, ex: "tnt_runn"
			candidates (list[str]): Every valid value
		Returns:
			str: The hint, empty when nothing is close enough

		Examples:
			>>> Validation.suggest("tnt_runn", ["tnt_run", "spleef"])
			"did you mean 'tnt_run'?"
			>>> Validation.suggest("zzzzz", ["tnt_run"])
			''
		"""
		close: list[str] = get_close_matches(value, candidates, n=1)
		return f"did you mean '{close[0]}'?" if close else ""

	@staticmethod
	def declared_folders() -> set[str]:
		""" Mode folders holding a main.py, excluding the engine helpers.

		Returns:
			set[str]: Folder names, ex: {"tnt_run", "spleef"}
		"""
		return {entry.name for entry in MODES_FOLDER.iterdir()
			if entry.is_dir() and entry.name not in RESERVED_FOLDERS and (entry / "main.py").is_file()}

	@staticmethod
	def check_modes() -> list[Problem]:
		""" Every mode has a unique id, a folder, a sane player range and a declared group.

		Returns:
			list[Problem]: The failures found
		"""
		problems: list[Problem] = []
		folders: set[str] = Validation.declared_folders()
		seen: set[str] = set()

		for mode in MODES:
			if mode.id in seen:
				problems.append(Problem(f"mode '{mode.id}' is declared twice in MODES"))
			seen.add(mode.id)

			if mode.id not in folders:
				problems.append(Problem(
					f"mode '{mode.id}' has no folder src/datapack/modes/{mode.id}/main.py",
					Validation.suggest(mode.id, sorted(folders))))

			if mode.min_players < 1:
				problems.append(Problem(f"mode '{mode.id}' has min_players={mode.min_players}, expected 1 or more"))
			if mode.max_players is not None and mode.max_players < mode.min_players:
				problems.append(Problem(
					f"mode '{mode.id}' has max_players={mode.max_players} below min_players={mode.min_players}"))

		for group_id, modes in grouped_modes().items():
			if len(modes) > 1 and group_id not in GROUPS_BY_ID:
				problems.append(Problem(
					f"group '{group_id}' gathers {len(modes)} modes but is missing from GROUPS",
					Validation.suggest(group_id, sorted(GROUPS_BY_ID))))
		return problems

	@staticmethod
	def referenced_maps() -> dict[str, set[str]]:
		""" Every map id referenced by a generated function, mapped to the functions using it.

		Returns:
			dict[str, set[str]]: Map id -> function paths
		"""
		referenced: dict[str, set[str]] = {}
		for path, function in Mem.ctx.data.functions.items():
			text: str = function.text
			names: list[str] = MAP_CONDITION_PATTERN.findall(text)
			for raw in CHOOSE_MAP_PATTERN.findall(text):
				names.extend(json.loads(raw))
			for name in names:
				referenced.setdefault(name, set()).add(path)
		return referenced

	@staticmethod
	def check_maps() -> list[Problem]:
		""" Every referenced map is either generated or a known world map.

		Returns:
			list[Problem]: The failures found
		"""
		known: set[str] = set(generated_maps) | MAPS_OUTSIDE_REGISTRY
		problems: list[Problem] = []
		for name, paths in sorted(Validation.referenced_maps().items()):
			if name not in known:
				problems.append(Problem(
					f"unknown map '{name}' referenced by {sorted(paths)[0]}",
					Validation.suggest(name, sorted(generated_maps))))
		return problems

	@staticmethod
	def report_unvoted() -> None:
		""" Log the modes that generate but never reach the vote, and the groups nobody uses. """
		unvoted: list[str] = sorted(Validation.declared_folders() - {mode.id for mode in MODES})
		if unvoted:
			stp.info(f"{len(unvoted)} mode(s) generated but absent from the vote: {', '.join(unvoted)}")

		used: set[str] = {group_id for group_id, modes in grouped_modes().items() if len(modes) > 1}
		unused: list[str] = sorted(group.id for group in GROUPS if group.id not in used)
		if unused:
			stp.warning(f"{len(unused)} group(s) declared but unused: {', '.join(unused)}")

	@staticmethod
	def run() -> None:
		""" Run every check, then stop the build when something is wrong.

		Raises:
			ValueError: When at least one check failed
		"""
		problems: list[Problem] = Validation.check_modes() + Validation.check_maps()
		Validation.report_unvoted()
		if problems:
			listed: str = "\n".join(f"  {problem.render()}" for problem in problems)
			raise ValueError(f"{len(problems)} declaration problem(s):\n{listed}")

