
## This file is auto-generated by the script 'generate_survival_folder.py'
## Don't edit it manually but the script instead

spreadplayers 90112 90143 5 56 under 180 false @s

## Assurance commands
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if entity @s[y=0,dy=99] run spreadplayers 90112 90143 5 56 under 180 false @s
execute at @s if block ~ ~-1 ~ barrier run spreadplayers 90112 90143 5 56 under 180 false @s

